// The hiit/strength_training authoring surface (docs/ARCHITECTURE.md's "Real
// exercise picker" design, the user's own explicit choice over a simpler placeholder or a
// free-text syntax): the athlete picks real exercises from Garmin's own 1,527-entry catalog
// (data/exerciseCatalog.json, generated by scripts/generate_exercise_catalog.py from the
// installed garminconnect package), each with reps-or-time, optional weight, optional rest
// steps. Unlike running's text-syntax editor, there is no separate text representation -- this
// editor's own item list *is* the canonical authored content, converted straight to
// PlannedWorkoutStepIn[] for the API (itemsToApiSteps) with no intermediate parse step.
//
// The authored content is a flat top-level list of *items*, each either a standalone exercise/
// rest or a *set*: a group of several exercises/rests repeated together N times (e.g. "3 rounds
// of squat, push-up, rest") -- the user's own explicit ask, added after the first version only
// supported one repeat wrapping the entire workout. The backend already handled this generically
// (`planned_workouts.py::build_workout_segment` walks every `repeat_until_steps_cmplt` marker
// independently, the same mechanism running's own multi-`Nx`-block text syntax already relies
// on), so this is a frontend-only extension -- no API/schema change needed. A set's own
// `repeat_from_step`/`step_index` range in the wire format is exactly its own children, so
// multiple sets (and standalone steps before/after/between them) coexist in one workout the same
// way multiple `Nx` blocks already coexist in a running workout's text.
import { useEffect, useState } from "react";

import type { PlannedWorkoutStepIn, PlannedWorkoutStepOut } from "../api/types";
import "../styles/exerciseStepEditor.css";

export interface ExerciseCatalogEntry {
  name: string;
  category: string;
  categoryLabel: string;
  exercise: string;
}

const MAX_RESULTS = 20;
// A rough guess (a controlled-tempo rep commonly takes 2-4s), matching planned_workouts.py's own
// _ASSUMED_SECONDS_PER_REP exactly -- display-only, never sent to Garmin.
const ASSUMED_SECONDS_PER_REP = 3;

// Dynamically imported (not a static `import ... from "../data/exerciseCatalog.json"`) so this
// ~230KB reference table -- only ever needed by the hiit/strength_training tier -- lands in its
// own code-split chunk rather than bloating the main app-shell bundle past vite-plugin-pwa's own
// 2MB precache limit (confirmed: a static import pushed the shell bundle to 2.24MB and broke the
// production build). `ScheduleWorkoutForm` calls `preloadExerciseCatalog()` unconditionally on
// mount so the fetch is usually already resolved by the time the athlete picks an exercise sport
// and opens the picker.
let catalog: ExerciseCatalogEntry[] | null = null;
let catalogPromise: Promise<ExerciseCatalogEntry[]> | null = null;

export function preloadExerciseCatalog(): Promise<ExerciseCatalogEntry[]> {
  catalogPromise ??= import("../data/exerciseCatalog.json").then((mod) => {
    catalog = mod.default as ExerciseCatalogEntry[];
    return catalog;
  });
  return catalogPromise;
}

// Lower is more relevant. Without this, a plain, simple exercise (e.g. "Squat", the bare
// category with no specific variant -- Garmin's own connect.garmin.com/app/exercises/SQUAT/SQUAT)
// could never appear for its own obvious query: every category's specific variants also carry
// that category's label (e.g. all ~100 SQUAT-category entries have categoryLabel "Squat"), so a
// plain substring match against a 1,527-entry catalog puts well over MAX_RESULTS entries in a
// three-way tie for "squat" -- confirmed live, where the bare "Squat" entry ranked 95th and
// never reached the (then-unordered) top 20. Ranking exact/prefix name matches first fixes this
// without dropping the broader "search by category" behavior category-label matches provide.
function matchRank(entry: ExerciseCatalogEntry, q: string): number {
  const name = entry.name.toLowerCase();
  if (name === q) return 0;
  if (name.startsWith(q)) return 1;
  if (name.includes(q)) return 2;
  return 3; // categoryLabel-only match -- caller already filtered to a real match of some kind
}

function matchingCatalogEntries(q: string): ExerciseCatalogEntry[] {
  if (q.length < 2 || catalog == null) return [];
  const matches = catalog.filter(
    (entry) =>
      entry.name.toLowerCase().includes(q) || entry.categoryLabel.toLowerCase().includes(q),
  );
  matches.sort((a, b) => matchRank(a, q) - matchRank(b, q));
  return matches;
}

export function searchExerciseCatalog(
  query: string,
  limit: number = MAX_RESULTS,
): ExerciseCatalogEntry[] {
  return matchingCatalogEntries(query.trim().toLowerCase()).slice(0, limit);
}

/** How many entries `searchExerciseCatalog` would match in total, ignoring any `limit` --
 * lets a caller offer "load more" only when there's actually more to load, without re-running
 * the same filter+sort twice per render. */
export function countExerciseCatalogMatches(query: string): number {
  return matchingCatalogEntries(query.trim().toLowerCase()).length;
}

/** The catalog's own display name for an already-picked (category, exerciseName) pair -- used to
 * re-populate the search box's text when editing a previously-saved workout, since the saved row
 * only carries the raw codes, not the display name. Falls back to a title-cased category when no
 * exact catalog match is found (e.g. a category-only pick with no specific variant). */
function catalogDisplayName(category: string | null, exerciseName: string | null): string {
  if (!category) return "";
  const wantExercise = exerciseName || category;
  const match = catalog?.find((e) => e.category === category && e.exercise === wantExercise);
  return match?.name ?? category.replace(/_/g, " ");
}

export interface ExerciseEntry {
  key: number; // React list key only, never sent to the API
  kind: "exercise" | "rest";
  exerciseQuery: string; // the search box's current text
  exerciseCategory: string | null;
  exerciseName: string | null;
  durationType: "reps" | "time";
  durationReps: string;
  durationTimeS: string;
  weightKg: string;
  comment: string;
}

/** A "set": several exercises/rests repeated together N times (e.g. "3 rounds of squat,
 * push-up, rest"). `repeatCount` of "" or "1" means "just run through it once" -- same
 * "no marker means no repeat" contract save_planned_workout already uses. Its own `comment`
 * lives on the repeat_until_steps_cmplt marker row -- lost if repeatCount stays at 1, since no
 * marker row is ever emitted then (see itemsToApiSteps). */
export interface ExerciseGroup {
  key: number;
  repeatCount: string;
  comment: string;
  entries: ExerciseEntry[];
}

export type ExerciseItem =
  { type: "entry"; entry: ExerciseEntry } | { type: "group"; group: ExerciseGroup };

let nextEntryKey = 0;

export function emptyExerciseEntry(): ExerciseEntry {
  return {
    key: nextEntryKey++,
    kind: "exercise",
    exerciseQuery: "",
    exerciseCategory: null,
    exerciseName: null,
    durationType: "reps",
    durationReps: "10",
    durationTimeS: "30",
    weightKg: "",
    comment: "",
  };
}

export function emptyRestEntry(): ExerciseEntry {
  return {
    key: nextEntryKey++,
    kind: "rest",
    exerciseQuery: "",
    exerciseCategory: null,
    exerciseName: null,
    durationType: "time",
    durationReps: "",
    durationTimeS: "60",
    weightKg: "",
    comment: "",
  };
}

export function emptyGroup(): ExerciseGroup {
  return { key: nextEntryKey++, repeatCount: "3", comment: "", entries: [] };
}

function stepOutToEntry(s: PlannedWorkoutStepOut): ExerciseEntry {
  return {
    key: nextEntryKey++,
    kind: s.intensity === "rest" ? "rest" : "exercise",
    exerciseQuery: catalogDisplayName(s.exercise_category, s.exercise_name),
    exerciseCategory: s.exercise_category,
    exerciseName: s.exercise_name,
    durationType: s.duration_type === "reps" ? "reps" : "time",
    durationReps: s.duration_reps != null ? String(s.duration_reps) : "",
    durationTimeS: s.duration_time_s != null ? String(s.duration_time_s) : "",
    weightKg: s.weight_kg != null ? String(s.weight_kg) : "",
    comment: s.comment ?? "",
  };
}

function entryToStep(e: ExerciseEntry, stepIndex: number): PlannedWorkoutStepIn {
  if (e.kind === "rest") {
    return {
      step_index: stepIndex,
      duration_type: "time",
      duration_time_s: Number(e.durationTimeS) || 0,
      intensity: "rest",
      comment: e.comment.trim() || null,
    };
  }
  return {
    step_index: stepIndex,
    duration_type: e.durationType,
    duration_reps: e.durationType === "reps" ? Number(e.durationReps) || 0 : null,
    duration_time_s: e.durationType === "time" ? Number(e.durationTimeS) || 0 : null,
    intensity: "active",
    exercise_category: e.exerciseCategory,
    exercise_name: e.exerciseName ?? "",
    weight_kg: e.weightKg ? Number(e.weightKg) : null,
    comment: e.comment.trim() || null,
  };
}

function entryDurationS(e: ExerciseEntry): number {
  if (e.kind === "rest" || e.durationType === "time") {
    return Number(e.durationTimeS) || 0;
  }
  return (Number(e.durationReps) || 0) * ASSUMED_SECONDS_PER_REP;
}

/** Converts saved PlannedWorkoutStepOut rows back into editable items, for editing an
 * already-saved workout. Each `repeat_until_steps_cmplt` marker becomes one `group` item
 * spanning exactly its own `[repeat_from_step, step_index)` children; everything else becomes a
 * standalone `entry` item, in step_index order -- the exact inverse of `itemsToApiSteps`. */
export function apiStepsToItems(steps: PlannedWorkoutStepOut[]): ExerciseItem[] {
  const sorted = [...steps].sort((a, b) => a.step_index - b.step_index);
  const consumed = new Set<number>();
  for (const s of sorted) {
    if (s.duration_type === "repeat_until_steps_cmplt" && s.repeat_from_step != null) {
      for (let i = s.repeat_from_step; i < s.step_index; i++) consumed.add(i);
    }
  }

  const items: ExerciseItem[] = [];
  for (const s of sorted) {
    if (s.duration_type === "repeat_until_steps_cmplt") {
      const from = s.repeat_from_step ?? 0;
      const children = sorted.filter((c) => c.step_index >= from && c.step_index < s.step_index);
      items.push({
        type: "group",
        group: {
          key: nextEntryKey++,
          repeatCount: s.repeat_count != null ? String(s.repeat_count) : "",
          comment: s.comment ?? "",
          entries: children.map(stepOutToEntry),
        },
      });
      continue;
    }
    if (consumed.has(s.step_index)) continue; // already included as a group's own child above
    items.push({ type: "entry", entry: stepOutToEntry(s) });
  }
  return items;
}

/** The editor's own item list -> the wire shape, assigning step_index sequentially and
 * appending a trailing repeat_until_steps_cmplt marker after each group's own children (mirrors
 * save_planned_workout's own "no marker means no repeat" contract). Multiple groups, and
 * standalone entries before/after/between them, all coexist correctly -- build_workout_segment
 * on the backend already walks every marker independently. */
export function itemsToApiSteps(items: ExerciseItem[]): PlannedWorkoutStepIn[] {
  const steps: PlannedWorkoutStepIn[] = [];
  for (const item of items) {
    if (item.type === "entry") {
      steps.push(entryToStep(item.entry, steps.length));
      continue;
    }
    const startIndex = steps.length;
    for (const e of item.group.entries) {
      steps.push(entryToStep(e, steps.length));
    }
    const count = Number(item.group.repeatCount);
    if (
      item.group.repeatCount &&
      Number.isFinite(count) &&
      count > 1 &&
      item.group.entries.length > 0
    ) {
      steps.push({
        step_index: steps.length,
        duration_type: "repeat_until_steps_cmplt",
        repeat_from_step: startIndex,
        repeat_count: count,
        comment: item.group.comment.trim() || null,
      });
    }
  }
  return steps;
}

/** Display-only estimate, matching planned_workouts.py::_estimate_exercise_duration_s exactly
 * (assumed seconds/rep, real seconds for a time-based or rest step), times each group's own
 * repeat count. */
export function estimateItemsDurationS(items: ExerciseItem[]): number {
  let total = 0;
  for (const item of items) {
    if (item.type === "entry") {
      total += entryDurationS(item.entry);
      continue;
    }
    const perRound = item.group.entries.reduce((sum, e) => sum + entryDurationS(e), 0);
    const count = Number(item.group.repeatCount);
    const multiplier = item.group.repeatCount && Number.isFinite(count) && count > 1 ? count : 1;
    total += perRound * multiplier;
  }
  return total;
}

function ExerciseEntryRow({
  entry,
  onUpdate,
  onRemove,
  onMoveUp,
  onMoveDown,
  pickerOpenFor,
  setPickerOpenFor,
}: {
  entry: ExerciseEntry;
  onUpdate: (patch: Partial<ExerciseEntry>) => void;
  onRemove: () => void;
  /** Omitted (not just a no-op) at whichever end of its own list this entry is already at, so
   * the button can be disabled there instead of silently doing nothing. */
  onMoveUp?: () => void;
  onMoveDown?: () => void;
  pickerOpenFor: number | null;
  setPickerOpenFor: (key: number | null) => void;
}) {
  // How many results to show for THIS row's own search -- local, not part of `entry` (a plain
  // data object that also feeds itemsToApiSteps/the saved workout, which this has nothing to do
  // with). Reset to the default page size whenever the query text itself changes, so "load more"
  // on one search doesn't linger once the athlete starts typing a different one.
  const [resultLimit, setResultLimit] = useState(MAX_RESULTS);
  const results = searchExerciseCatalog(entry.exerciseQuery, resultLimit);
  const totalMatches = countExerciseCatalogMatches(entry.exerciseQuery);

  return (
    <div className="exercise-step-editor__entry">
      <div className="exercise-step-editor__row">
        {entry.kind === "exercise" ? (
          <>
            <div className="exercise-step-editor__search">
              <input
                className="input"
                placeholder="Search exercises… (e.g. Bench Press)"
                value={entry.exerciseQuery}
                onChange={(e) => {
                  onUpdate({
                    exerciseQuery: e.target.value,
                    exerciseCategory: null,
                    exerciseName: null,
                  });
                  setPickerOpenFor(entry.key);
                  setResultLimit(MAX_RESULTS);
                }}
                onFocus={() => setPickerOpenFor(entry.key)}
                onBlur={() => setTimeout(() => setPickerOpenFor(null), 150)}
              />
              {pickerOpenFor === entry.key && entry.exerciseQuery.trim().length >= 2 && (
                <ul className="exercise-step-editor__results">
                  {results.map((r) => (
                    <li key={`${r.category}:${r.exercise}`}>
                      <button
                        type="button"
                        onMouseDown={() =>
                          onUpdate({
                            exerciseCategory: r.category,
                            exerciseName: r.exercise === r.category ? "" : r.exercise,
                            exerciseQuery: r.name,
                          })
                        }
                      >
                        {r.name}
                        <span className="exercise-step-editor__category">{r.categoryLabel}</span>
                      </button>
                    </li>
                  ))}
                  {results.length === 0 && (
                    <li className="exercise-step-editor__no-results">No matching exercise</li>
                  )}
                  {totalMatches > results.length && (
                    <li>
                      <button
                        type="button"
                        className="exercise-step-editor__load-more"
                        onMouseDown={(e) => {
                          // Unlike picking a result (where closing the dropdown afterward is the
                          // whole point), this must NOT blur the search input -- that would fire
                          // its own onBlur close-the-dropdown timeout and immediately undo the
                          // expansion this click just asked for. preventDefault on mousedown stops
                          // the browser from shifting focus to the button at all.
                          e.preventDefault();
                          setResultLimit((n) => n + MAX_RESULTS);
                        }}
                      >
                        Load more ({totalMatches - results.length} more)
                      </button>
                    </li>
                  )}
                </ul>
              )}
            </div>

            <select
              className="input"
              value={entry.durationType}
              onChange={(e) => onUpdate({ durationType: e.target.value as "reps" | "time" })}
            >
              <option value="reps">reps</option>
              <option value="time">time</option>
            </select>

            <input
              className="input exercise-step-editor__number"
              type="number"
              min="1"
              value={entry.durationType === "reps" ? entry.durationReps : entry.durationTimeS}
              onChange={(e) =>
                onUpdate(
                  entry.durationType === "reps"
                    ? { durationReps: e.target.value }
                    : { durationTimeS: e.target.value },
                )
              }
            />
            <span className="chart-note">{entry.durationType === "reps" ? "reps" : "sec"}</span>

            <input
              className="input exercise-step-editor__number"
              type="number"
              min="0"
              step="0.5"
              placeholder="kg"
              value={entry.weightKg}
              onChange={(e) => onUpdate({ weightKg: e.target.value })}
            />
          </>
        ) : (
          <>
            <span className="exercise-step-editor__rest-label">Rest</span>
            <input
              className="input exercise-step-editor__number"
              type="number"
              min="1"
              value={entry.durationTimeS}
              onChange={(e) => onUpdate({ durationTimeS: e.target.value })}
            />
            <span className="chart-note">sec</span>
          </>
        )}

        <div className="exercise-step-editor__row-actions">
          <button
            type="button"
            className="button exercise-step-editor__move"
            onClick={onMoveUp}
            disabled={onMoveUp == null}
            aria-label="Move up"
            title="Move up"
          >
            ↑
          </button>
          <button
            type="button"
            className="button exercise-step-editor__move"
            onClick={onMoveDown}
            disabled={onMoveDown == null}
            aria-label="Move down"
            title="Move down"
          >
            ↓
          </button>
          <button type="button" className="button" onClick={onRemove}>
            Remove
          </button>
        </div>
      </div>
      <input
        className="input exercise-step-editor__comment"
        placeholder="Comment (optional)"
        value={entry.comment}
        onChange={(e) => onUpdate({ comment: e.target.value })}
      />
    </div>
  );
}

export function ExerciseStepEditor({
  items,
  onChange,
}: {
  items: ExerciseItem[];
  onChange: (items: ExerciseItem[]) => void;
}) {
  const [pickerOpenFor, setPickerOpenFor] = useState<number | null>(null);
  // Forces a re-render once the dynamically-imported catalog resolves, in case the athlete opens
  // the search box before ScheduleWorkoutForm's own mount-time preload has finished.
  const [, setCatalogReady] = useState(0);
  useEffect(() => {
    let cancelled = false;
    void preloadExerciseCatalog().then(() => {
      if (!cancelled) setCatalogReady((n) => n + 1);
    });
    return () => {
      cancelled = true;
    };
  }, []);

  function updateAt(index: number, next: ExerciseItem) {
    onChange(items.map((it, i) => (i === index ? next : it)));
  }

  function removeAt(index: number) {
    onChange(items.filter((_, i) => i !== index));
  }

  function updateGroupEntries(index: number, group: ExerciseGroup, entries: ExerciseEntry[]) {
    updateAt(index, { type: "group", group: { ...group, entries } });
  }

  // Reordering a standalone exercise/rest or a whole set among its siblings -- step_index is
  // assigned purely by array position at save time (itemsToApiSteps), so swapping two entries
  // here is the entire feature; nothing else in the wire format needs to change.
  function moveItemAt(index: number, direction: -1 | 1) {
    const target = index + direction;
    if (target < 0 || target >= items.length) return;
    const next = [...items];
    [next[index], next[target]] = [next[target]!, next[index]!];
    onChange(next);
  }

  // Same idea, one level down: reordering exercises/rests within one set.
  function moveGroupEntryAt(
    index: number,
    group: ExerciseGroup,
    entryIndex: number,
    direction: -1 | 1,
  ) {
    const target = entryIndex + direction;
    if (target < 0 || target >= group.entries.length) return;
    const nextEntries = [...group.entries];
    [nextEntries[entryIndex], nextEntries[target]] = [
      nextEntries[target]!,
      nextEntries[entryIndex]!,
    ];
    updateGroupEntries(index, group, nextEntries);
  }

  return (
    <div className="exercise-step-editor">
      {items.map((item, index) =>
        item.type === "entry" ? (
          <ExerciseEntryRow
            key={item.entry.key}
            entry={item.entry}
            onUpdate={(patch) =>
              updateAt(index, { type: "entry", entry: { ...item.entry, ...patch } })
            }
            onRemove={() => removeAt(index)}
            onMoveUp={index > 0 ? () => moveItemAt(index, -1) : undefined}
            onMoveDown={index < items.length - 1 ? () => moveItemAt(index, 1) : undefined}
            pickerOpenFor={pickerOpenFor}
            setPickerOpenFor={setPickerOpenFor}
          />
        ) : (
          <div key={item.group.key} className="exercise-step-editor__group">
            <div className="exercise-step-editor__group-head">
              <strong>Set</strong>
              <label className="field exercise-step-editor__group-repeat">
                Repeat
                <input
                  className="input exercise-step-editor__number"
                  type="number"
                  min="1"
                  placeholder="e.g. 3"
                  value={item.group.repeatCount}
                  onChange={(e) =>
                    updateAt(index, {
                      type: "group",
                      group: { ...item.group, repeatCount: e.target.value },
                    })
                  }
                />
              </label>
              <span className="chart-note">times</span>
              <input
                className="input exercise-step-editor__comment"
                placeholder="Comment (optional)"
                value={item.group.comment}
                onChange={(e) =>
                  updateAt(index, {
                    type: "group",
                    group: { ...item.group, comment: e.target.value },
                  })
                }
              />
              <div className="exercise-step-editor__row-actions">
                <button
                  type="button"
                  className="button exercise-step-editor__move"
                  onClick={() => moveItemAt(index, -1)}
                  disabled={index === 0}
                  aria-label="Move set up"
                  title="Move set up"
                >
                  ↑
                </button>
                <button
                  type="button"
                  className="button exercise-step-editor__move"
                  onClick={() => moveItemAt(index, 1)}
                  disabled={index === items.length - 1}
                  aria-label="Move set down"
                  title="Move set down"
                >
                  ↓
                </button>
                <button type="button" className="button" onClick={() => removeAt(index)}>
                  Remove set
                </button>
              </div>
            </div>

            {item.group.entries.map((entry, entryIndex) => (
              <ExerciseEntryRow
                key={entry.key}
                entry={entry}
                onUpdate={(patch) =>
                  updateGroupEntries(
                    index,
                    item.group,
                    item.group.entries.map((e) => (e.key === entry.key ? { ...e, ...patch } : e)),
                  )
                }
                onRemove={() =>
                  updateGroupEntries(
                    index,
                    item.group,
                    item.group.entries.filter((e) => e.key !== entry.key),
                  )
                }
                onMoveUp={
                  entryIndex > 0
                    ? () => moveGroupEntryAt(index, item.group, entryIndex, -1)
                    : undefined
                }
                onMoveDown={
                  entryIndex < item.group.entries.length - 1
                    ? () => moveGroupEntryAt(index, item.group, entryIndex, 1)
                    : undefined
                }
                pickerOpenFor={pickerOpenFor}
                setPickerOpenFor={setPickerOpenFor}
              />
            ))}

            <div className="planned-workout__actions">
              <button
                type="button"
                className="button"
                onClick={() =>
                  updateGroupEntries(index, item.group, [
                    ...item.group.entries,
                    emptyExerciseEntry(),
                  ])
                }
              >
                + Add exercise to set
              </button>
              <button
                type="button"
                className="button"
                onClick={() =>
                  updateGroupEntries(index, item.group, [...item.group.entries, emptyRestEntry()])
                }
              >
                + Add rest to set
              </button>
            </div>
          </div>
        ),
      )}

      <div className="planned-workout__actions">
        <button
          type="button"
          className="button"
          onClick={() => onChange([...items, { type: "entry", entry: emptyExerciseEntry() }])}
        >
          + Add exercise
        </button>
        <button
          type="button"
          className="button"
          onClick={() => onChange([...items, { type: "entry", entry: emptyRestEntry() }])}
        >
          + Add rest
        </button>
        <button
          type="button"
          className="button"
          onClick={() => onChange([...items, { type: "group", group: emptyGroup() }])}
        >
          + Add a set of exercises
        </button>
      </div>
    </div>
  );
}
