// The hiit/strength_training authoring surface (docs/adr/0015-scheduled-workouts.md's "Real
// exercise picker" design, the user's own explicit choice over a simpler placeholder or a
// free-text syntax): the athlete picks real exercises from Garmin's own 1,527-entry catalog
// (data/exerciseCatalog.json, generated by scripts/generate_exercise_catalog.py from the
// installed garminconnect package), each with reps-or-time, optional weight, optional rest
// steps, and an optional "repeat as N sets" wrapper. Unlike running's text-syntax editor, there
// is no separate text representation -- this editor's own entry list *is* the canonical
// authored content, converted straight to PlannedWorkoutStepIn[] for the API (entriesToApiSteps)
// with no intermediate parse step.
import { useEffect, useState } from "react";

import type { PlannedWorkoutStepIn, PlannedWorkoutStepOut } from "../api/types";
import "../styles/exerciseStepEditor.css";

export interface ExerciseCatalogEntry {
  name: string;
  category: string;
  categoryLabel: string;
  exercise: string;
}

const MAX_RESULTS = 20;
// A rough guess (a controlled-tempo rep commonly takes 2-4s), matching planned_workouts.py's own
// _ASSUMED_SECONDS_PER_REP exactly -- display-only, never sent to Garmin.
const ASSUMED_SECONDS_PER_REP = 3;

// Dynamically imported (not a static `import ... from "../data/exerciseCatalog.json"`) so this
// ~230KB reference table -- only ever needed by the hiit/strength_training tier -- lands in its
// own code-split chunk rather than bloating the main app-shell bundle past vite-plugin-pwa's own
// 2MB precache limit (confirmed: a static import pushed the shell bundle to 2.24MB and broke the
// production build). `ScheduleWorkoutForm` calls `preloadExerciseCatalog()` unconditionally on
// mount so the fetch is usually already resolved by the time the athlete picks an exercise sport
// and opens the picker.
let catalog: ExerciseCatalogEntry[] | null = null;
let catalogPromise: Promise<ExerciseCatalogEntry[]> | null = null;

export function preloadExerciseCatalog(): Promise<ExerciseCatalogEntry[]> {
  catalogPromise ??= import("../data/exerciseCatalog.json").then((mod) => {
    catalog = mod.default as ExerciseCatalogEntry[];
    return catalog;
  });
  return catalogPromise;
}

export function searchExerciseCatalog(query: string): ExerciseCatalogEntry[] {
  const q = query.trim().toLowerCase();
  if (q.length < 2 || catalog == null) return [];
  const results: ExerciseCatalogEntry[] = [];
  for (const entry of catalog) {
    if (entry.name.toLowerCase().includes(q) || entry.categoryLabel.toLowerCase().includes(q)) {
      results.push(entry);
      if (results.length >= MAX_RESULTS) break;
    }
  }
  return results;
}

/** The catalog's own display name for an already-picked (category, exerciseName) pair -- used to
 * re-populate the search box's text when editing a previously-saved workout, since the saved row
 * only carries the raw codes, not the display name. Falls back to a title-cased category when no
 * exact catalog match is found (e.g. a category-only pick with no specific variant). */
function catalogDisplayName(category: string | null, exerciseName: string | null): string {
  if (!category) return "";
  const wantExercise = exerciseName || category;
  const match = catalog?.find((e) => e.category === category && e.exercise === wantExercise);
  return match?.name ?? category.replace(/_/g, " ");
}

export interface ExerciseEntry {
  key: number; // React list key only, never sent to the API
  kind: "exercise" | "rest";
  exerciseQuery: string; // the search box's current text
  exerciseCategory: string | null;
  exerciseName: string | null;
  durationType: "reps" | "time";
  durationReps: string;
  durationTimeS: string;
  weightKg: string;
}

let nextEntryKey = 0;

export function emptyExerciseEntry(): ExerciseEntry {
  return {
    key: nextEntryKey++,
    kind: "exercise",
    exerciseQuery: "",
    exerciseCategory: null,
    exerciseName: null,
    durationType: "reps",
    durationReps: "10",
    durationTimeS: "30",
    weightKg: "",
  };
}

export function emptyRestEntry(): ExerciseEntry {
  return {
    key: nextEntryKey++,
    kind: "rest",
    exerciseQuery: "",
    exerciseCategory: null,
    exerciseName: null,
    durationType: "time",
    durationReps: "",
    durationTimeS: "60",
    weightKg: "",
  };
}

/** Converts saved PlannedWorkoutStepOut rows back into editable entries, for editing an
 * already-saved workout. A trailing repeat_until_steps_cmplt marker (if any) is consumed into
 * the returned repeatCount rather than becoming its own entry -- this editor always wraps the
 * *entire* entry list in one repeat group (matching entriesToApiSteps below), never a partial
 * selection. */
export function apiStepsToEntries(steps: PlannedWorkoutStepOut[]): {
  entries: ExerciseEntry[];
  repeatCount: string;
} {
  const sorted = [...steps].sort((a, b) => a.step_index - b.step_index);
  const repeatMarker = sorted.find((s) => s.duration_type === "repeat_until_steps_cmplt");
  const leaves = sorted.filter((s) => s.duration_type !== "repeat_until_steps_cmplt");
  const entries: ExerciseEntry[] = leaves.map((s) => ({
    key: nextEntryKey++,
    kind: s.intensity === "rest" ? "rest" : "exercise",
    exerciseQuery: catalogDisplayName(s.exercise_category, s.exercise_name),
    exerciseCategory: s.exercise_category,
    exerciseName: s.exercise_name,
    durationType: s.duration_type === "reps" ? "reps" : "time",
    durationReps: s.duration_reps != null ? String(s.duration_reps) : "",
    durationTimeS: s.duration_time_s != null ? String(s.duration_time_s) : "",
    weightKg: s.weight_kg != null ? String(s.weight_kg) : "",
  }));
  return {
    entries,
    repeatCount: repeatMarker?.repeat_count != null ? String(repeatMarker.repeat_count) : "",
  };
}

/** The editor's own entry list -> the wire shape, assigning step_index in list order and
 * appending a trailing repeat_until_steps_cmplt marker when repeatCount is a real count > 1
 * (mirrors save_planned_workout's own "no marker means no repeat" contract). */
export function entriesToApiSteps(
  entries: ExerciseEntry[],
  repeatCount: string,
): PlannedWorkoutStepIn[] {
  const steps: PlannedWorkoutStepIn[] = entries.map((e, i) => {
    if (e.kind === "rest") {
      return {
        step_index: i,
        duration_type: "time",
        duration_time_s: Number(e.durationTimeS) || 0,
        intensity: "rest",
      };
    }
    return {
      step_index: i,
      duration_type: e.durationType,
      duration_reps: e.durationType === "reps" ? Number(e.durationReps) || 0 : null,
      duration_time_s: e.durationType === "time" ? Number(e.durationTimeS) || 0 : null,
      intensity: "active",
      exercise_category: e.exerciseCategory,
      exercise_name: e.exerciseName ?? "",
      weight_kg: e.weightKg ? Number(e.weightKg) : null,
    };
  });
  const count = Number(repeatCount);
  if (repeatCount && Number.isFinite(count) && count > 1 && steps.length > 0) {
    steps.push({
      step_index: steps.length,
      duration_type: "repeat_until_steps_cmplt",
      repeat_from_step: 0,
      repeat_count: count,
    });
  }
  return steps;
}

/** Display-only estimate, matching planned_workouts.py::_estimate_exercise_duration_s exactly
 * (assumed seconds/rep, real seconds for a time-based or rest step), times the repeat count. */
export function estimateExerciseDurationS(entries: ExerciseEntry[], repeatCount: string): number {
  const perSet = entries.reduce((sum, e) => {
    if (e.kind === "rest" || e.durationType === "time") {
      return sum + (Number(e.durationTimeS) || 0);
    }
    return sum + (Number(e.durationReps) || 0) * ASSUMED_SECONDS_PER_REP;
  }, 0);
  const count = Number(repeatCount);
  const multiplier = repeatCount && Number.isFinite(count) && count > 1 ? count : 1;
  return perSet * multiplier;
}

export function ExerciseStepEditor({
  entries,
  onChange,
  repeatCount,
  onRepeatCountChange,
}: {
  entries: ExerciseEntry[];
  onChange: (entries: ExerciseEntry[]) => void;
  repeatCount: string;
  onRepeatCountChange: (value: string) => void;
}) {
  const [pickerOpenFor, setPickerOpenFor] = useState<number | null>(null);
  // Forces a re-render once the dynamically-imported catalog resolves, in case the athlete opens
  // the search box before ScheduleWorkoutForm's own mount-time preload has finished.
  const [, setCatalogReady] = useState(0);
  useEffect(() => {
    let cancelled = false;
    void preloadExerciseCatalog().then(() => {
      if (!cancelled) setCatalogReady((n) => n + 1);
    });
    return () => {
      cancelled = true;
    };
  }, []);

  function updateEntry(key: number, patch: Partial<ExerciseEntry>) {
    onChange(entries.map((e) => (e.key === key ? { ...e, ...patch } : e)));
  }

  function pickExercise(key: number, catalogEntry: ExerciseCatalogEntry) {
    updateEntry(key, {
      exerciseCategory: catalogEntry.category,
      exerciseName: catalogEntry.exercise === catalogEntry.category ? "" : catalogEntry.exercise,
      exerciseQuery: catalogEntry.name,
    });
    setPickerOpenFor(null);
  }

  return (
    <div className="exercise-step-editor">
      {entries.map((entry) => (
        <div key={entry.key} className="exercise-step-editor__row">
          {entry.kind === "exercise" ? (
            <>
              <div className="exercise-step-editor__search">
                <input
                  className="input"
                  placeholder="Search exercises… (e.g. Bench Press)"
                  value={entry.exerciseQuery}
                  onChange={(e) => {
                    updateEntry(entry.key, {
                      exerciseQuery: e.target.value,
                      exerciseCategory: null,
                      exerciseName: null,
                    });
                    setPickerOpenFor(entry.key);
                  }}
                  onFocus={() => setPickerOpenFor(entry.key)}
                  onBlur={() => setTimeout(() => setPickerOpenFor(null), 150)}
                />
                {pickerOpenFor === entry.key && entry.exerciseQuery.trim().length >= 2 && (
                  <ul className="exercise-step-editor__results">
                    {searchExerciseCatalog(entry.exerciseQuery).map((r) => (
                      <li key={`${r.category}:${r.exercise}`}>
                        <button type="button" onMouseDown={() => pickExercise(entry.key, r)}>
                          {r.name}
                          <span className="exercise-step-editor__category">
                            {r.categoryLabel}
                          </span>
                        </button>
                      </li>
                    ))}
                    {searchExerciseCatalog(entry.exerciseQuery).length === 0 && (
                      <li className="exercise-step-editor__no-results">No matching exercise</li>
                    )}
                  </ul>
                )}
              </div>

              <select
                className="input"
                value={entry.durationType}
                onChange={(e) =>
                  updateEntry(entry.key, { durationType: e.target.value as "reps" | "time" })
                }
              >
                <option value="reps">reps</option>
                <option value="time">time</option>
              </select>

              <input
                className="input exercise-step-editor__number"
                type="number"
                min="1"
                value={entry.durationType === "reps" ? entry.durationReps : entry.durationTimeS}
                onChange={(e) =>
                  updateEntry(
                    entry.key,
                    entry.durationType === "reps"
                      ? { durationReps: e.target.value }
                      : { durationTimeS: e.target.value },
                  )
                }
              />
              <span className="chart-note">{entry.durationType === "reps" ? "reps" : "sec"}</span>

              <input
                className="input exercise-step-editor__number"
                type="number"
                min="0"
                step="0.5"
                placeholder="kg"
                value={entry.weightKg}
                onChange={(e) => updateEntry(entry.key, { weightKg: e.target.value })}
              />
            </>
          ) : (
            <>
              <span className="exercise-step-editor__rest-label">Rest</span>
              <input
                className="input exercise-step-editor__number"
                type="number"
                min="1"
                value={entry.durationTimeS}
                onChange={(e) => updateEntry(entry.key, { durationTimeS: e.target.value })}
              />
              <span className="chart-note">sec</span>
            </>
          )}

          <button
            type="button"
            className="button exercise-step-editor__remove"
            onClick={() => onChange(entries.filter((e) => e.key !== entry.key))}
          >
            Remove
          </button>
        </div>
      ))}

      <div className="planned-workout__actions">
        <button
          type="button"
          className="button"
          onClick={() => onChange([...entries, emptyExerciseEntry()])}
        >
          + Add exercise
        </button>
        <button
          type="button"
          className="button"
          onClick={() => onChange([...entries, emptyRestEntry()])}
        >
          + Add rest
        </button>
      </div>

      {entries.length > 1 && (
        <label className="field">
          Repeat as sets
          <input
            className="input"
            type="number"
            min="2"
            placeholder="e.g. 3"
            value={repeatCount}
            onChange={(e) => onRepeatCountChange(e.target.value)}
          />
        </label>
      )}
    </div>
  );
}
