// The hiit/strength_training authoring surface (docs/adr/0015-scheduled-workouts.md's "Real
// exercise picker" design, the user's own explicit choice over a simpler placeholder or a
// free-text syntax): the athlete picks real exercises from Garmin's own 1,527-entry catalog
// (data/exerciseCatalog.json, generated by scripts/generate_exercise_catalog.py from the
// installed garminconnect package), each with reps-or-time, optional weight, optional rest
// steps. Unlike running's text-syntax editor, there is no separate text representation -- this
// editor's own item list *is* the canonical authored content, converted straight to
// PlannedWorkoutStepIn[] for the API (itemsToApiSteps) with no intermediate parse step.
//
// The authored content is a flat top-level list of *items*, each either a standalone exercise/
// rest or a *set*: a group of several exercises/rests repeated together N times (e.g. "3 rounds
// of squat, push-up, rest") -- the user's own explicit ask, added after the first version only
// supported one repeat wrapping the entire workout. The backend already handled this generically
// (`planned_workouts.py::build_workout_segment` walks every `repeat_until_steps_cmplt` marker
// independently, the same mechanism running's own multi-`Nx`-block text syntax already relies
// on), so this is a frontend-only extension -- no API/schema change needed. A set's own
// `repeat_from_step`/`step_index` range in the wire format is exactly its own children, so
// multiple sets (and standalone steps before/after/between them) coexist in one workout the same
// way multiple `Nx` blocks already coexist in a running workout's text.
import { useEffect, useState } from "react";

import type { PlannedWorkoutStepIn, PlannedWorkoutStepOut } from "../api/types";
import "../styles/exerciseStepEditor.css";

export interface ExerciseCatalogEntry {
  name: string;
  category: string;
  categoryLabel: string;
  exercise: string;
}

const MAX_RESULTS = 20;
// A rough guess (a controlled-tempo rep commonly takes 2-4s), matching planned_workouts.py's own
// _ASSUMED_SECONDS_PER_REP exactly -- display-only, never sent to Garmin.
const ASSUMED_SECONDS_PER_REP = 3;

// Dynamically imported (not a static `import ... from "../data/exerciseCatalog.json"`) so this
// ~230KB reference table -- only ever needed by the hiit/strength_training tier -- lands in its
// own code-split chunk rather than bloating the main app-shell bundle past vite-plugin-pwa's own
// 2MB precache limit (confirmed: a static import pushed the shell bundle to 2.24MB and broke the
// production build). `ScheduleWorkoutForm` calls `preloadExerciseCatalog()` unconditionally on
// mount so the fetch is usually already resolved by the time the athlete picks an exercise sport
// and opens the picker.
let catalog: ExerciseCatalogEntry[] | null = null;
let catalogPromise: Promise<ExerciseCatalogEntry[]> | null = null;

export function preloadExerciseCatalog(): Promise<ExerciseCatalogEntry[]> {
  catalogPromise ??= import("../data/exerciseCatalog.json").then((mod) => {
    catalog = mod.default as ExerciseCatalogEntry[];
    return catalog;
  });
  return catalogPromise;
}

export function searchExerciseCatalog(query: string): ExerciseCatalogEntry[] {
  const q = query.trim().toLowerCase();
  if (q.length < 2 || catalog == null) return [];
  const results: ExerciseCatalogEntry[] = [];
  for (const entry of catalog) {
    if (entry.name.toLowerCase().includes(q) || entry.categoryLabel.toLowerCase().includes(q)) {
      results.push(entry);
      if (results.length >= MAX_RESULTS) break;
    }
  }
  return results;
}

/** The catalog's own display name for an already-picked (category, exerciseName) pair -- used to
 * re-populate the search box's text when editing a previously-saved workout, since the saved row
 * only carries the raw codes, not the display name. Falls back to a title-cased category when no
 * exact catalog match is found (e.g. a category-only pick with no specific variant). */
function catalogDisplayName(category: string | null, exerciseName: string | null): string {
  if (!category) return "";
  const wantExercise = exerciseName || category;
  const match = catalog?.find((e) => e.category === category && e.exercise === wantExercise);
  return match?.name ?? category.replace(/_/g, " ");
}

export interface ExerciseEntry {
  key: number; // React list key only, never sent to the API
  kind: "exercise" | "rest";
  exerciseQuery: string; // the search box's current text
  exerciseCategory: string | null;
  exerciseName: string | null;
  durationType: "reps" | "time";
  durationReps: string;
  durationTimeS: string;
  weightKg: string;
  comment: string;
}

/** A "set": several exercises/rests repeated together N times (e.g. "3 rounds of squat,
 * push-up, rest"). `repeatCount` of "" or "1" means "just run through it once" -- same
 * "no marker means no repeat" contract save_planned_workout already uses. Its own `comment`
 * lives on the repeat_until_steps_cmplt marker row -- lost if repeatCount stays at 1, since no
 * marker row is ever emitted then (see itemsToApiSteps). */
export interface ExerciseGroup {
  key: number;
  repeatCount: string;
  comment: string;
  entries: ExerciseEntry[];
}

export type ExerciseItem =
  { type: "entry"; entry: ExerciseEntry } | { type: "group"; group: ExerciseGroup };

let nextEntryKey = 0;

export function emptyExerciseEntry(): ExerciseEntry {
  return {
    key: nextEntryKey++,
    kind: "exercise",
    exerciseQuery: "",
    exerciseCategory: null,
    exerciseName: null,
    durationType: "reps",
    durationReps: "10",
    durationTimeS: "30",
    weightKg: "",
    comment: "",
  };
}

export function emptyRestEntry(): ExerciseEntry {
  return {
    key: nextEntryKey++,
    kind: "rest",
    exerciseQuery: "",
    exerciseCategory: null,
    exerciseName: null,
    durationType: "time",
    durationReps: "",
    durationTimeS: "60",
    weightKg: "",
    comment: "",
  };
}

export function emptyGroup(): ExerciseGroup {
  return { key: nextEntryKey++, repeatCount: "3", comment: "", entries: [] };
}

function stepOutToEntry(s: PlannedWorkoutStepOut): ExerciseEntry {
  return {
    key: nextEntryKey++,
    kind: s.intensity === "rest" ? "rest" : "exercise",
    exerciseQuery: catalogDisplayName(s.exercise_category, s.exercise_name),
    exerciseCategory: s.exercise_category,
    exerciseName: s.exercise_name,
    durationType: s.duration_type === "reps" ? "reps" : "time",
    durationReps: s.duration_reps != null ? String(s.duration_reps) : "",
    durationTimeS: s.duration_time_s != null ? String(s.duration_time_s) : "",
    weightKg: s.weight_kg != null ? String(s.weight_kg) : "",
    comment: s.comment ?? "",
  };
}

function entryToStep(e: ExerciseEntry, stepIndex: number): PlannedWorkoutStepIn {
  if (e.kind === "rest") {
    return {
      step_index: stepIndex,
      duration_type: "time",
      duration_time_s: Number(e.durationTimeS) || 0,
      intensity: "rest",
      comment: e.comment.trim() || null,
    };
  }
  return {
    step_index: stepIndex,
    duration_type: e.durationType,
    duration_reps: e.durationType === "reps" ? Number(e.durationReps) || 0 : null,
    duration_time_s: e.durationType === "time" ? Number(e.durationTimeS) || 0 : null,
    intensity: "active",
    exercise_category: e.exerciseCategory,
    exercise_name: e.exerciseName ?? "",
    weight_kg: e.weightKg ? Number(e.weightKg) : null,
    comment: e.comment.trim() || null,
  };
}

function entryDurationS(e: ExerciseEntry): number {
  if (e.kind === "rest" || e.durationType === "time") {
    return Number(e.durationTimeS) || 0;
  }
  return (Number(e.durationReps) || 0) * ASSUMED_SECONDS_PER_REP;
}

/** Converts saved PlannedWorkoutStepOut rows back into editable items, for editing an
 * already-saved workout. Each `repeat_until_steps_cmplt` marker becomes one `group` item
 * spanning exactly its own `[repeat_from_step, step_index)` children; everything else becomes a
 * standalone `entry` item, in step_index order -- the exact inverse of `itemsToApiSteps`. */
export function apiStepsToItems(steps: PlannedWorkoutStepOut[]): ExerciseItem[] {
  const sorted = [...steps].sort((a, b) => a.step_index - b.step_index);
  const consumed = new Set<number>();
  for (const s of sorted) {
    if (s.duration_type === "repeat_until_steps_cmplt" && s.repeat_from_step != null) {
      for (let i = s.repeat_from_step; i < s.step_index; i++) consumed.add(i);
    }
  }

  const items: ExerciseItem[] = [];
  for (const s of sorted) {
    if (s.duration_type === "repeat_until_steps_cmplt") {
      const from = s.repeat_from_step ?? 0;
      const children = sorted.filter((c) => c.step_index >= from && c.step_index < s.step_index);
      items.push({
        type: "group",
        group: {
          key: nextEntryKey++,
          repeatCount: s.repeat_count != null ? String(s.repeat_count) : "",
          comment: s.comment ?? "",
          entries: children.map(stepOutToEntry),
        },
      });
      continue;
    }
    if (consumed.has(s.step_index)) continue; // already included as a group's own child above
    items.push({ type: "entry", entry: stepOutToEntry(s) });
  }
  return items;
}

/** The editor's own item list -> the wire shape, assigning step_index sequentially and
 * appending a trailing repeat_until_steps_cmplt marker after each group's own children (mirrors
 * save_planned_workout's own "no marker means no repeat" contract). Multiple groups, and
 * standalone entries before/after/between them, all coexist correctly -- build_workout_segment
 * on the backend already walks every marker independently. */
export function itemsToApiSteps(items: ExerciseItem[]): PlannedWorkoutStepIn[] {
  const steps: PlannedWorkoutStepIn[] = [];
  for (const item of items) {
    if (item.type === "entry") {
      steps.push(entryToStep(item.entry, steps.length));
      continue;
    }
    const startIndex = steps.length;
    for (const e of item.group.entries) {
      steps.push(entryToStep(e, steps.length));
    }
    const count = Number(item.group.repeatCount);
    if (
      item.group.repeatCount &&
      Number.isFinite(count) &&
      count > 1 &&
      item.group.entries.length > 0
    ) {
      steps.push({
        step_index: steps.length,
        duration_type: "repeat_until_steps_cmplt",
        repeat_from_step: startIndex,
        repeat_count: count,
        comment: item.group.comment.trim() || null,
      });
    }
  }
  return steps;
}

/** Display-only estimate, matching planned_workouts.py::_estimate_exercise_duration_s exactly
 * (assumed seconds/rep, real seconds for a time-based or rest step), times each group's own
 * repeat count. */
export function estimateItemsDurationS(items: ExerciseItem[]): number {
  let total = 0;
  for (const item of items) {
    if (item.type === "entry") {
      total += entryDurationS(item.entry);
      continue;
    }
    const perRound = item.group.entries.reduce((sum, e) => sum + entryDurationS(e), 0);
    const count = Number(item.group.repeatCount);
    const multiplier = item.group.repeatCount && Number.isFinite(count) && count > 1 ? count : 1;
    total += perRound * multiplier;
  }
  return total;
}

function ExerciseEntryRow({
  entry,
  onUpdate,
  onRemove,
  pickerOpenFor,
  setPickerOpenFor,
}: {
  entry: ExerciseEntry;
  onUpdate: (patch: Partial<ExerciseEntry>) => void;
  onRemove: () => void;
  pickerOpenFor: number | null;
  setPickerOpenFor: (key: number | null) => void;
}) {
  return (
    <div className="exercise-step-editor__entry">
      <div className="exercise-step-editor__row">
        {entry.kind === "exercise" ? (
          <>
            <div className="exercise-step-editor__search">
              <input
                className="input"
                placeholder="Search exercises… (e.g. Bench Press)"
                value={entry.exerciseQuery}
                onChange={(e) => {
                  onUpdate({
                    exerciseQuery: e.target.value,
                    exerciseCategory: null,
                    exerciseName: null,
                  });
                  setPickerOpenFor(entry.key);
                }}
                onFocus={() => setPickerOpenFor(entry.key)}
                onBlur={() => setTimeout(() => setPickerOpenFor(null), 150)}
              />
              {pickerOpenFor === entry.key && entry.exerciseQuery.trim().length >= 2 && (
                <ul className="exercise-step-editor__results">
                  {searchExerciseCatalog(entry.exerciseQuery).map((r) => (
                    <li key={`${r.category}:${r.exercise}`}>
                      <button
                        type="button"
                        onMouseDown={() =>
                          onUpdate({
                            exerciseCategory: r.category,
                            exerciseName: r.exercise === r.category ? "" : r.exercise,
                            exerciseQuery: r.name,
                          })
                        }
                      >
                        {r.name}
                        <span className="exercise-step-editor__category">{r.categoryLabel}</span>
                      </button>
                    </li>
                  ))}
                  {searchExerciseCatalog(entry.exerciseQuery).length === 0 && (
                    <li className="exercise-step-editor__no-results">No matching exercise</li>
                  )}
                </ul>
              )}
            </div>

            <select
              className="input"
              value={entry.durationType}
              onChange={(e) => onUpdate({ durationType: e.target.value as "reps" | "time" })}
            >
              <option value="reps">reps</option>
              <option value="time">time</option>
            </select>

            <input
              className="input exercise-step-editor__number"
              type="number"
              min="1"
              value={entry.durationType === "reps" ? entry.durationReps : entry.durationTimeS}
              onChange={(e) =>
                onUpdate(
                  entry.durationType === "reps"
                    ? { durationReps: e.target.value }
                    : { durationTimeS: e.target.value },
                )
              }
            />
            <span className="chart-note">{entry.durationType === "reps" ? "reps" : "sec"}</span>

            <input
              className="input exercise-step-editor__number"
              type="number"
              min="0"
              step="0.5"
              placeholder="kg"
              value={entry.weightKg}
              onChange={(e) => onUpdate({ weightKg: e.target.value })}
            />
          </>
        ) : (
          <>
            <span className="exercise-step-editor__rest-label">Rest</span>
            <input
              className="input exercise-step-editor__number"
              type="number"
              min="1"
              value={entry.durationTimeS}
              onChange={(e) => onUpdate({ durationTimeS: e.target.value })}
            />
            <span className="chart-note">sec</span>
          </>
        )}

        <button type="button" className="button exercise-step-editor__remove" onClick={onRemove}>
          Remove
        </button>
      </div>
      <input
        className="input exercise-step-editor__comment"
        placeholder="Comment (optional)"
        value={entry.comment}
        onChange={(e) => onUpdate({ comment: e.target.value })}
      />
    </div>
  );
}

export function ExerciseStepEditor({
  items,
  onChange,
}: {
  items: ExerciseItem[];
  onChange: (items: ExerciseItem[]) => void;
}) {
  const [pickerOpenFor, setPickerOpenFor] = useState<number | null>(null);
  // Forces a re-render once the dynamically-imported catalog resolves, in case the athlete opens
  // the search box before ScheduleWorkoutForm's own mount-time preload has finished.
  const [, setCatalogReady] = useState(0);
  useEffect(() => {
    let cancelled = false;
    void preloadExerciseCatalog().then(() => {
      if (!cancelled) setCatalogReady((n) => n + 1);
    });
    return () => {
      cancelled = true;
    };
  }, []);

  function updateAt(index: number, next: ExerciseItem) {
    onChange(items.map((it, i) => (i === index ? next : it)));
  }

  function removeAt(index: number) {
    onChange(items.filter((_, i) => i !== index));
  }

  function updateGroupEntries(index: number, group: ExerciseGroup, entries: ExerciseEntry[]) {
    updateAt(index, { type: "group", group: { ...group, entries } });
  }

  return (
    <div className="exercise-step-editor">
      {items.map((item, index) =>
        item.type === "entry" ? (
          <ExerciseEntryRow
            key={item.entry.key}
            entry={item.entry}
            onUpdate={(patch) =>
              updateAt(index, { type: "entry", entry: { ...item.entry, ...patch } })
            }
            onRemove={() => removeAt(index)}
            pickerOpenFor={pickerOpenFor}
            setPickerOpenFor={setPickerOpenFor}
          />
        ) : (
          <div key={item.group.key} className="exercise-step-editor__group">
            <div className="exercise-step-editor__group-head">
              <strong>Set</strong>
              <label className="field exercise-step-editor__group-repeat">
                Repeat
                <input
                  className="input exercise-step-editor__number"
                  type="number"
                  min="1"
                  placeholder="e.g. 3"
                  value={item.group.repeatCount}
                  onChange={(e) =>
                    updateAt(index, {
                      type: "group",
                      group: { ...item.group, repeatCount: e.target.value },
                    })
                  }
                />
              </label>
              <span className="chart-note">times</span>
              <input
                className="input exercise-step-editor__comment"
                placeholder="Comment (optional)"
                value={item.group.comment}
                onChange={(e) =>
                  updateAt(index, {
                    type: "group",
                    group: { ...item.group, comment: e.target.value },
                  })
                }
              />
              <button
                type="button"
                className="button exercise-step-editor__remove"
                onClick={() => removeAt(index)}
              >
                Remove set
              </button>
            </div>

            {item.group.entries.map((entry) => (
              <ExerciseEntryRow
                key={entry.key}
                entry={entry}
                onUpdate={(patch) =>
                  updateGroupEntries(
                    index,
                    item.group,
                    item.group.entries.map((e) => (e.key === entry.key ? { ...e, ...patch } : e)),
                  )
                }
                onRemove={() =>
                  updateGroupEntries(
                    index,
                    item.group,
                    item.group.entries.filter((e) => e.key !== entry.key),
                  )
                }
                pickerOpenFor={pickerOpenFor}
                setPickerOpenFor={setPickerOpenFor}
              />
            ))}

            <div className="planned-workout__actions">
              <button
                type="button"
                className="button"
                onClick={() =>
                  updateGroupEntries(index, item.group, [
                    ...item.group.entries,
                    emptyExerciseEntry(),
                  ])
                }
              >
                + Add exercise to set
              </button>
              <button
                type="button"
                className="button"
                onClick={() =>
                  updateGroupEntries(index, item.group, [...item.group.entries, emptyRestEntry()])
                }
              >
                + Add rest to set
              </button>
            </div>
          </div>
        ),
      )}

      <div className="planned-workout__actions">
        <button
          type="button"
          className="button"
          onClick={() => onChange([...items, { type: "entry", entry: emptyExerciseEntry() }])}
        >
          + Add exercise
        </button>
        <button
          type="button"
          className="button"
          onClick={() => onChange([...items, { type: "entry", entry: emptyRestEntry() }])}
        >
          + Add rest
        </button>
        <button
          type="button"
          className="button"
          onClick={() => onChange([...items, { type: "group", group: emptyGroup() }])}
        >
          + Add a set of exercises
        </button>
      </div>
    </div>
  );
}
