"""add planned_workout scheduled_time

Revision ID: 00625484e7c8
Revises: 5abb34ed02b4
Create Date: 2026-09-04 23:23:38.081673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00625484e7c8'
down_revision: Union[str, Sequence[str], None] = '5abb34ed02b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planned_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_time', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planned_workout', schema=None) as batch_op:
        batch_op.drop_column('scheduled_time')

    # ### end Alembic commands ###
