"""add goal table

Revision ID: 0506390e24dc
Revises: 8a84d68166a5
Create Date: 2026-08-19 22:06:50.012118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0506390e24dc'
down_revision: Union[str, Sequence[str], None] = '8a84d68166a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.String(), nullable=False),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('target_distance_m', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'period_type', 'period_start', name='uq_goal_identity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal')
    # ### end Alembic commands ###
