"""add planned_workout completed_at

Revision ID: 17c9c6538b90
Revises: 4ddb14a42f38
Create Date: 2026-09-08 08:58:04.151487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c9c6538b90'
down_revision: Union[str, Sequence[str], None] = '4ddb14a42f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planned_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planned_workout', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
