"""add athlete profile fields and max_hr_source

Revision ID: 1c7cf1b44f2c
Revises: c3cb96164eca
Create Date: 2026-09-07 16:21:52.008139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c7cf1b44f2c'
down_revision: Union[str, Sequence[str], None] = 'c3cb96164eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('height_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(), nullable=True))

    with op.batch_alter_table('performance_daily_rollup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_hr_source', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_daily_rollup', schema=None) as batch_op:
        batch_op.drop_column('max_hr_source')

    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.drop_column('sex')
        batch_op.drop_column('height_cm')
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###
