"""add home_lat and home_lon to athlete

Settable via GET/PUT /settings/profile -- the athlete's own default location, used as the
input to weather_forecast.py's forecast fetch since no other location concept exists on this
schema. Both nullable, additive, no backfill.

Revision ID: 23a2f038143c
Revises: 967384f4d517
Create Date: 2026-09-13 20:35:56.564445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a2f038143c'
down_revision: Union[str, Sequence[str], None] = '967384f4d517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('home_lon', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.drop_column('home_lon')
        batch_op.drop_column('home_lat')

    # ### end Alembic commands ###
