"""add calendar_feed_token to athlete

Revision ID: 2e16e2853432
Revises: ae1765d37ab5
Create Date: 2026-09-06 17:29:33.456340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e16e2853432'
down_revision: Union[str, Sequence[str], None] = 'ae1765d37ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_feed_token_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('calendar_feed_created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.drop_column('calendar_feed_created_at')
        batch_op.drop_column('calendar_feed_token_hash')

    # ### end Alembic commands ###
