"""Add activity_trim_override

Revision ID: 33dcfc4728df
Revises: 7ba10d68e333
Create Date: 2026-08-23 16:03:52.281655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33dcfc4728df'
down_revision: Union[str, Sequence[str], None] = '7ba10d68e333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_trim_override',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('activity_start_time_utc', sa.DateTime(), nullable=False),
    sa.Column('trim_start_s', sa.Float(), nullable=True),
    sa.Column('trim_end_s', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'activity_start_time_utc', name='uq_activity_trim_override_identity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_trim_override')
    # ### end Alembic commands ###
