"""initial schema

Revision ID: 35c217c541f2
Revises:
Create Date: 2026-08-02 19:57:55.308129

"""
import datetime as dt
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c217c541f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Fixed, not regenerated per-environment: this is the one-and-only athlete row for a
# single-tenant deployment. Generated once via `ULID()` at authoring time.
SEED_ATHLETE_ID = "01KZ2P1FN0AWE6ASCDQ9X847WP"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('unit_preference', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_definition',
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('unit_si', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('value_type', sa.String(), nullable=False),
    sa.Column('chart_hints', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('first_seen_source', sa.String(), nullable=False),
    sa.Column('is_promoted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('metric_key')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'manufacturer', 'product', 'serial_number', name='uq_device_athlete_identity')
    )
    op.create_table('health_stream',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('parquet_path', sa.Text(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['metric_key'], ['metric_definition.metric_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'metric_key', 'year_month', 'source', name='uq_health_stream_identity')
    )
    op.create_table('ingest_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('watermark_from', sa.DateTime(), nullable=True),
    sa.Column('watermark_to', sa.DateTime(), nullable=True),
    sa.Column('items_seen', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_run', schema=None) as batch_op:
        batch_op.create_index('ix_ingest_run_athlete_source', ['athlete_id', 'source'], unique=False)

    op.create_table('raw_object',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('source_locator', sa.Text(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'sha256', name='uq_raw_object_athlete_sha256')
    )
    with op.batch_alter_table('raw_object', schema=None) as batch_op:
        batch_op.create_index('ix_raw_object_athlete_source_kind', ['athlete_id', 'source', 'kind'], unique=False)

    op.create_table('activity',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('start_time_utc', sa.DateTime(), nullable=False),
    sa.Column('utc_offset_s', sa.Integer(), nullable=False),
    sa.Column('tz_name', sa.String(), nullable=True),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('sub_sport', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('moving_duration_s', sa.Float(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('primary_source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index('ix_activity_athlete_start', ['athlete_id', 'start_time_utc'], unique=False)

    op.create_table('health_observation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('observed_at_utc', sa.DateTime(), nullable=False),
    sa.Column('local_date', sa.String(), nullable=False),
    sa.Column('interval_start', sa.DateTime(), nullable=True),
    sa.Column('interval_end', sa.DateTime(), nullable=True),
    sa.Column('aggregation', sa.String(), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('raw_object_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['metric_key'], ['metric_definition.metric_key'], ),
    sa.ForeignKeyConstraint(['raw_object_id'], ['raw_object.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'metric_key', 'observed_at_utc', 'source', name='uq_health_observation_identity')
    )
    with op.batch_alter_table('health_observation', schema=None) as batch_op:
        batch_op.create_index('ix_health_observation_athlete_date', ['athlete_id', 'local_date'], unique=False)

    op.create_table('sleep_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('local_date', sa.String(), nullable=False),
    sa.Column('start_time_utc', sa.DateTime(), nullable=False),
    sa.Column('end_time_utc', sa.DateTime(), nullable=False),
    sa.Column('total_sleep_s', sa.Float(), nullable=True),
    sa.Column('sleep_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('raw_object_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['raw_object_id'], ['raw_object.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'local_date', 'source', name='uq_sleep_session_identity')
    )
    op.create_table('activity_metric',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(length=26), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['metric_key'], ['metric_definition.metric_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'activity_id', 'metric_key', 'source', name='uq_activity_metric_identity')
    )
    op.create_table('activity_source_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(length=26), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('raw_object_id', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['raw_object_id'], ['raw_object.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'source', 'external_id', name='uq_activity_source_link_identity')
    )
    with op.batch_alter_table('activity_source_link', schema=None) as batch_op:
        batch_op.create_index('ix_activity_source_link_activity', ['athlete_id', 'activity_id'], unique=False)

    op.create_table('activity_stream',
    sa.Column('activity_id', sa.String(length=26), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('parquet_path', sa.Text(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('channels', sa.Text(), nullable=False),
    sa.Column('sample_rate_hint', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('lap',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(length=26), nullable=False),
    sa.Column('lap_index', sa.Integer(), nullable=False),
    sa.Column('start_time_utc', sa.DateTime(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('avg_speed_mps', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'activity_id', 'lap_index', name='uq_lap_identity')
    )
    op.create_table('merge_decision',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('matched_activity_id', sa.String(length=26), nullable=True),
    sa.Column('candidate_ref', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=False),
    sa.Column('inputs', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['matched_activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_geom',
    sa.Column('activity_id', sa.String(length=26), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('encoded_polyline', sa.Text(), nullable=True),
    sa.Column('simplified_polyline', sa.Text(), nullable=True),
    sa.Column('min_lat', sa.Float(), nullable=True),
    sa.Column('min_lng', sa.Float(), nullable=True),
    sa.Column('max_lat', sa.Float(), nullable=True),
    sa.Column('max_lng', sa.Float(), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_lng', sa.Float(), nullable=True),
    sa.Column('end_lat', sa.Float(), nullable=True),
    sa.Column('end_lng', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    with op.batch_alter_table('route_geom', schema=None) as batch_op:
        batch_op.create_index('ix_route_geom_athlete_bbox', ['athlete_id', 'min_lat', 'min_lng', 'max_lat', 'max_lng'], unique=False)

    op.create_table('sleep_stage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('sleep_session_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('start_time_utc', sa.DateTime(), nullable=False),
    sa.Column('end_time_utc', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['sleep_session_id'], ['sleep_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('split',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(length=26), nullable=False),
    sa.Column('split_index', sa.Integer(), nullable=False),
    sa.Column('split_type', sa.String(), nullable=True),
    sa.Column('start_time_utc', sa.DateTime(), nullable=True),
    sa.Column('end_time_utc', sa.DateTime(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'activity_id', 'split_index', name='uq_split_identity')
    )
    # ### end Alembic commands ###

    athlete_table = sa.table(
        "athlete",
        sa.column("id", sa.String),
        sa.column("display_name", sa.String),
        sa.column("timezone", sa.String),
        sa.column("unit_preference", sa.String),
        sa.column("created_at", sa.DateTime),
    )
    op.bulk_insert(
        athlete_table,
        [
            {
                "id": SEED_ATHLETE_ID,
                "display_name": "Jerome",
                "timezone": "UTC",
                "unit_preference": "metric",
                # Naive UTC, matching the naive-UTC convention documented in db/schema.py.
                "created_at": dt.datetime.now(dt.UTC).replace(tzinfo=None),
            }
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('split')
    op.drop_table('sleep_stage')
    with op.batch_alter_table('route_geom', schema=None) as batch_op:
        batch_op.drop_index('ix_route_geom_athlete_bbox')

    op.drop_table('route_geom')
    op.drop_table('merge_decision')
    op.drop_table('lap')
    op.drop_table('activity_stream')
    with op.batch_alter_table('activity_source_link', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_source_link_activity')

    op.drop_table('activity_source_link')
    op.drop_table('activity_metric')
    op.drop_table('sleep_session')
    with op.batch_alter_table('health_observation', schema=None) as batch_op:
        batch_op.drop_index('ix_health_observation_athlete_date')

    op.drop_table('health_observation')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_athlete_start')

    op.drop_table('activity')
    with op.batch_alter_table('raw_object', schema=None) as batch_op:
        batch_op.drop_index('ix_raw_object_athlete_source_kind')

    op.drop_table('raw_object')
    with op.batch_alter_table('ingest_run', schema=None) as batch_op:
        batch_op.drop_index('ix_ingest_run_athlete_source')

    op.drop_table('ingest_run')
    op.drop_table('health_stream')
    op.drop_table('device')
    op.drop_table('metric_definition')
    op.drop_table('athlete')
    # ### end Alembic commands ###
