"""add auth_login_attempt table for login lockout

Revision ID: 3b0b88022315
Revises: 5cc607c99bf7
Create Date: 2026-08-29 18:22:36.222685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b0b88022315'
down_revision: Union[str, Sequence[str], None] = '5cc607c99bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_login_attempt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_login_attempt', schema=None) as batch_op:
        batch_op.create_index('ix_auth_login_attempt_username_time', ['username', 'attempted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_login_attempt', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_login_attempt_username_time')

    op.drop_table('auth_login_attempt')
    # ### end Alembic commands ###
