"""add aerobic threshold columns to performance_daily_rollup

New independently-computed aerobic threshold ("LT1"/"VT1") pace and HR, alongside the existing
(unrenamed) anaerobic threshold_pace_s_per_km/threshold_hr_bpm columns -- see
performance_rollup.py's own docstring and vdot.py's AEROBIC_THRESHOLD_VO2MAX_FRACTION for the
model and its literature basis (Fathi et al. 2025; Esteve-Lanao et al. 2026). Additive, backfilled
on the next refresh_performance_rollup() run for every athlete (same full-recompute contract this
table already has), not by this migration itself -- existing rows just carry null for these three
columns until then.

Revision ID: 3de3df6b0072
Revises: d906425621ea
Create Date: 2026-09-12 21:01:05.914141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de3df6b0072'
down_revision: Union[str, Sequence[str], None] = 'd906425621ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_daily_rollup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aerobic_threshold_pace_s_per_km', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('aerobic_threshold_hr_bpm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('aerobic_threshold_hr_source', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_daily_rollup', schema=None) as batch_op:
        batch_op.drop_column('aerobic_threshold_hr_source')
        batch_op.drop_column('aerobic_threshold_hr_bpm')
        batch_op.drop_column('aerobic_threshold_pace_s_per_km')

    # ### end Alembic commands ###
