"""Add grade to bouldering_route_status_override

Revision ID: 4a71a0e55c10
Revises: 33dcfc4728df
Create Date: 2026-08-23 16:38:01.355963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a71a0e55c10'
down_revision: Union[str, Sequence[str], None] = '33dcfc4728df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bouldering_route_status_override', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))
        batch_op.alter_column('result',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bouldering_route_status_override', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
