"""allow more than one planned workout per day

Revision ID: 4ddb14a42f38
Revises: d9e61a1f78b5
Create Date: 2026-09-07 19:31:35.283306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ddb14a42f38'
down_revision: Union[str, Sequence[str], None] = 'd9e61a1f78b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planned_workout', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_planned_workout_identity'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planned_workout', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_planned_workout_identity'), ['athlete_id', 'local_date'])

    # ### end Alembic commands ###
