"""add planned_workout tables

Revision ID: 5abb34ed02b4
Revises: 3b0b88022315
Create Date: 2026-08-29 22:36:57.922342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5abb34ed02b4'
down_revision: Union[str, Sequence[str], None] = '3b0b88022315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planned_workout',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('local_date', sa.String(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('estimated_duration_s', sa.Float(), nullable=True),
    sa.Column('garmin_workout_id', sa.Integer(), nullable=True),
    sa.Column('garmin_scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('push_status', sa.String(), nullable=False),
    sa.Column('push_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'local_date', name='uq_planned_workout_identity')
    )
    op.create_table('planned_workout_step',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('planned_workout_id', sa.Integer(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('duration_type', sa.String(), nullable=True),
    sa.Column('duration_time_s', sa.Float(), nullable=True),
    sa.Column('duration_distance_m', sa.Float(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_low', sa.Float(), nullable=True),
    sa.Column('target_high', sa.Float(), nullable=True),
    sa.Column('target_hr_zone', sa.Integer(), nullable=True),
    sa.Column('cadence_low', sa.Integer(), nullable=True),
    sa.Column('cadence_high', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.String(), nullable=True),
    sa.Column('repeat_from_step', sa.Integer(), nullable=True),
    sa.Column('repeat_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['planned_workout_id'], ['planned_workout.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'planned_workout_id', 'step_index', name='uq_planned_workout_step_identity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planned_workout_step')
    op.drop_table('planned_workout')
    # ### end Alembic commands ###
