"""add athlete running load config

Revision ID: 5cc607c99bf7
Revises: 7a75859bf07f
Create Date: 2026-08-26 23:23:55.385589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc607c99bf7'
down_revision: Union[str, Sequence[str], None] = '7a75859bf07f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_running_load_config',
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('threshold_pace_sec_per_km', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('athlete_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('athlete_running_load_config')
    # ### end Alembic commands ###
