"""add manual name correction to activity_sport_override

Revision ID: 5f2cb9099973
Revises: d553c2e39bc5
Create Date: 2026-08-15 17:24:02.071058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2cb9099973'
down_revision: Union[str, Sequence[str], None] = 'd553c2e39bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_sport_override', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_sport_override', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
