"""rollups, notes, activity.local_date

Revision ID: 72c93cdc8cf9
Revises: c9ebfc30ba99
Create Date: 2026-08-03 14:24:18.656949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c93cdc8cf9'
down_revision: Union[str, Sequence[str], None] = 'c9ebfc30ba99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_rollup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('local_date', sa.String(), nullable=False),
    sa.Column('activity_count', sa.Integer(), nullable=False),
    sa.Column('activity_duration_s', sa.Float(), nullable=True),
    sa.Column('activity_moving_duration_s', sa.Float(), nullable=True),
    sa.Column('activity_distance_m', sa.Float(), nullable=True),
    sa.Column('activity_elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('activity_calories', sa.Float(), nullable=True),
    sa.Column('sleep_total_s', sa.Float(), nullable=True),
    sa.Column('sleep_score', sa.Float(), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'local_date', name='uq_day_rollup_identity')
    )
    op.create_table('health_metric_daily_rollup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('local_date', sa.String(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('value_sum', sa.Float(), nullable=True),
    sa.Column('value_avg', sa.Float(), nullable=True),
    sa.Column('value_min', sa.Float(), nullable=True),
    sa.Column('value_max', sa.Float(), nullable=True),
    sa.Column('value_last', sa.Float(), nullable=True),
    sa.Column('n_observations', sa.Integer(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['metric_key'], ['metric_definition.metric_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'local_date', 'metric_key', name='uq_health_rollup_identity')
    )
    with op.batch_alter_table('health_metric_daily_rollup', schema=None) as batch_op:
        batch_op.create_index('ix_health_rollup_athlete_date', ['athlete_id', 'local_date'], unique=False)

    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index('ix_note_athlete_entity', ['athlete_id', 'entity_type', 'entity_id'], unique=False)

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_date', sa.String(), nullable=True))
        batch_op.create_index('ix_activity_athlete_local_date', ['athlete_id', 'local_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_athlete_local_date')
        batch_op.drop_column('local_date')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index('ix_note_athlete_entity')

    op.drop_table('note')
    with op.batch_alter_table('health_metric_daily_rollup', schema=None) as batch_op:
        batch_op.drop_index('ix_health_rollup_athlete_date')

    op.drop_table('health_metric_daily_rollup')
    op.drop_table('day_rollup')
    # ### end Alembic commands ###
