"""add athlete credentials for phase 5 auth

Revision ID: 76b0bdab038a
Revises: 72c93cdc8cf9
Create Date: 2026-08-03 21:08:23.763728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b0bdab038a'
down_revision: Union[str, Sequence[str], None] = '72c93cdc8cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('api_key_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('api_key_created_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_athlete_username', ['username'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.drop_constraint('uq_athlete_username', type_='unique')
        batch_op.drop_column('api_key_created_at')
        batch_op.drop_column('api_key_hash')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
