"""add share_link

Revision ID: 7a75859bf07f
Revises: bc2cb42cdd7e
Create Date: 2026-08-24 22:54:15.395791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a75859bf07f'
down_revision: Union[str, Sequence[str], None] = 'bc2cb42cdd7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_share_link_token_hash')
    )
    with op.batch_alter_table('share_link', schema=None) as batch_op:
        batch_op.create_index('ix_share_link_athlete', ['athlete_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_link', schema=None) as batch_op:
        batch_op.drop_index('ix_share_link_athlete')

    op.drop_table('share_link')
    # ### end Alembic commands ###
