"""add carbohydrates_g and sodium_mg to activity and activity_sport_override

Revision ID: 7b3c41eaa110
Revises: 0506390e24dc
Create Date: 2026-08-21 22:04:15.129833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3c41eaa110'
down_revision: Union[str, Sequence[str], None] = '0506390e24dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carbohydrates_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sodium_mg', sa.Float(), nullable=True))

    with op.batch_alter_table('activity_sport_override', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carbohydrates_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sodium_mg', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_sport_override', schema=None) as batch_op:
        batch_op.drop_column('sodium_mg')
        batch_op.drop_column('carbohydrates_g')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('sodium_mg')
        batch_op.drop_column('carbohydrates_g')

    # ### end Alembic commands ###
