"""Add bouldering route status override and manual route tables

Revision ID: 7ba10d68e333
Revises: 93467b5a6399
Create Date: 2026-08-23 14:48:27.834584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba10d68e333'
down_revision: Union[str, Sequence[str], None] = '93467b5a6399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bouldering_manual_route',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('activity_start_time_utc', sa.DateTime(), nullable=False),
    sa.Column('manual_order', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('split_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'activity_start_time_utc', 'manual_order', name='uq_bouldering_manual_route_identity')
    )
    op.create_table('bouldering_route_status_override',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('activity_start_time_utc', sa.DateTime(), nullable=False),
    sa.Column('split_index', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'activity_start_time_utc', 'split_index', name='uq_bouldering_route_status_override_identity')
    )
    with op.batch_alter_table('split', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_manual', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('split', schema=None) as batch_op:
        batch_op.drop_column('is_manual')

    op.drop_table('bouldering_route_status_override')
    op.drop_table('bouldering_manual_route')
    # ### end Alembic commands ###
