"""add planned_workout_step exercise fields

Revision ID: 85ec81998a26
Revises: 00625484e7c8
Create Date: 2026-09-05 00:02:12.853145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ec81998a26'
down_revision: Union[str, Sequence[str], None] = '00625484e7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planned_workout_step', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_reps', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('exercise_category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('exercise_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('weight_kg', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planned_workout_step', schema=None) as batch_op:
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('exercise_name')
        batch_op.drop_column('exercise_category')
        batch_op.drop_column('duration_reps')

    # ### end Alembic commands ###
