"""add athlete hr zone config

Revision ID: 8a84d68166a5
Revises: 98feafa85853
Create Date: 2026-08-15 22:36:34.806023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a84d68166a5'
down_revision: Union[str, Sequence[str], None] = '98feafa85853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_hr_zone_config',
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('max_hr_bpm', sa.Float(), nullable=True),
    sa.Column('threshold_hr_bpm', sa.Float(), nullable=True),
    sa.Column('resting_hr_bpm', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('athlete_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('athlete_hr_zone_config')
    # ### end Alembic commands ###
