"""add planned_workout comment

Revision ID: 8fd062dbf1a9
Revises: d9f41d56aea6
Create Date: 2026-09-10 23:30:59.450945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd062dbf1a9'
down_revision: Union[str, Sequence[str], None] = 'd9f41d56aea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """A general note for the whole workout, read before any step -- distinct from
    planned_workout_step.comment's per-step scope. Pushed to Garmin as the workout's own
    `description` field. Additive, no backfill."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planned_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planned_workout', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
