"""Add climb_avg_hr and climb_max_hr to split

Revision ID: 93467b5a6399
Revises: 009385b68a22
Create Date: 2026-08-23 00:07:57.074992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93467b5a6399'
down_revision: Union[str, Sequence[str], None] = '009385b68a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('split', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climb_avg_hr', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('climb_max_hr', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('split', schema=None) as batch_op:
        batch_op.drop_column('climb_max_hr')
        batch_op.drop_column('climb_avg_hr')

    # ### end Alembic commands ###
