"""add week_start_day, time_format, default_view to athlete

Personalize settings (GET/PUT /settings/personalize) -- pure display preferences, never read by
any backend computation. NOT NULL with a server_default so existing athlete rows backfill
in-place during this ALTER TABLE rather than needing a separate data migration.

Revision ID: 9861c92c896b
Revises: 23a2f038143c
Create Date: 2026-09-15 23:00:28.512685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9861c92c896b'
down_revision: Union[str, Sequence[str], None] = '23a2f038143c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'week_start_day', sa.String(), nullable=False, server_default='monday'
            )
        )
        batch_op.add_column(
            sa.Column('time_format', sa.String(), nullable=False, server_default='24h')
        )
        batch_op.add_column(
            sa.Column('default_view', sa.String(), nullable=False, server_default='week')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.drop_column('default_view')
        batch_op.drop_column('time_format')
        batch_op.drop_column('week_start_day')

    # ### end Alembic commands ###
