"""add lap moving_duration_s

Revision ID: 98feafa85853
Revises: b0fb6b1994e2
Create Date: 2026-08-15 20:51:13.151051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98feafa85853'
down_revision: Union[str, Sequence[str], None] = 'b0fb6b1994e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moving_duration_s', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lap', schema=None) as batch_op:
        batch_op.drop_column('moving_duration_s')

    # ### end Alembic commands ###
