"""add planned_race

Revision ID: a361f567acfd
Revises: 8fd062dbf1a9
Create Date: 2026-09-10 23:19:12.688701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a361f567acfd'
down_revision: Union[str, Sequence[str], None] = '8fd062dbf1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """A single upcoming race on the calendar (planned_races.py) -- name/date/optional time,
    distance, and an optional target finish time. Deliberately not a planned_workout sport tier
    (no step model, no Garmin push); own id-keyed table, any number per athlete per date.
    Additive, no backfill."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planned_race',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('local_date', sa.String(), nullable=False),
    sa.Column('scheduled_time', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('target_duration_s', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planned_race')
    # ### end Alembic commands ###
