"""add activity_metric activity_id+metric_key index

Revision ID: a6c58d78f6fc
Revises: b3850d71d2a2
Create Date: 2026-08-05 23:46:22.986777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c58d78f6fc'
down_revision: Union[str, Sequence[str], None] = 'b3850d71d2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_metric', schema=None) as batch_op:
        batch_op.create_index('ix_activity_metric_activity_key', ['activity_id', 'metric_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_metric', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_metric_activity_key')

    # ### end Alembic commands ###
