"""add sleep_stage session index

A bare FK column isn't auto-indexed by SQLite. GET /sleep batch-fetches every returned session's
own stages in one `sleep_session_id IN (...)` query (api/routers/sleep.py) -- without this index
that fell back to a full sleep_stage table scan per lookup value, the dominant cost in a real
~7s GET /sleep call over ~1,400 nights of history. Additive, no backfill (an index needs no data
migration, just building).

Revision ID: aad9cbbed3d3
Revises: a361f567acfd
Create Date: 2026-09-12 17:47:32.587434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad9cbbed3d3'
down_revision: Union[str, Sequence[str], None] = 'a361f567acfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_stage', schema=None) as batch_op:
        batch_op.create_index('ix_sleep_stage_session', ['sleep_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_stage', schema=None) as batch_op:
        batch_op.drop_index('ix_sleep_stage_session')

    # ### end Alembic commands ###
