"""add performance_daily_rollup

Revision ID: ae1765d37ab5
Revises: 85ec81998a26
Create Date: 2026-09-06 00:10:18.666485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1765d37ab5'
down_revision: Union[str, Sequence[str], None] = '85ec81998a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_daily_rollup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('local_date', sa.String(), nullable=False),
    sa.Column('rolling_vdot', sa.Float(), nullable=True),
    sa.Column('max_hr_bpm', sa.Float(), nullable=True),
    sa.Column('threshold_pace_s_per_km', sa.Float(), nullable=True),
    sa.Column('threshold_hr_bpm', sa.Float(), nullable=True),
    sa.Column('threshold_hr_source', sa.String(), nullable=True),
    sa.Column('predicted_5k_s', sa.Float(), nullable=True),
    sa.Column('predicted_10k_s', sa.Float(), nullable=True),
    sa.Column('predicted_half_marathon_s', sa.Float(), nullable=True),
    sa.Column('predicted_marathon_s', sa.Float(), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'local_date', name='uq_performance_daily_rollup_identity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_daily_rollup')
    # ### end Alembic commands ###
