"""add activity_workout and activity_workout_step tables

Revision ID: b0fb6b1994e2
Revises: 5f2cb9099973
Create Date: 2026-08-15 17:49:21.671027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0fb6b1994e2'
down_revision: Union[str, Sequence[str], None] = '5f2cb9099973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_workout',
    sa.Column('activity_id', sa.String(length=26), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('activity_workout_step',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(length=26), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('duration_type', sa.String(), nullable=True),
    sa.Column('duration_time_s', sa.Float(), nullable=True),
    sa.Column('duration_distance_m', sa.Float(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_low_mps', sa.Float(), nullable=True),
    sa.Column('target_high_mps', sa.Float(), nullable=True),
    sa.Column('intensity', sa.String(), nullable=True),
    sa.Column('repeat_from_step', sa.Integer(), nullable=True),
    sa.Column('repeat_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'activity_id', 'step_index', name='uq_activity_workout_step_identity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_workout_step')
    op.drop_table('activity_workout')
    # ### end Alembic commands ###
