"""period rollups and fitness daily rollup

Revision ID: b3850d71d2a2
Revises: 76b0bdab038a
Create Date: 2026-08-04 00:36:19.733082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3850d71d2a2'
down_revision: Union[str, Sequence[str], None] = '76b0bdab038a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fitness_daily_rollup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('local_date', sa.String(), nullable=False),
    sa.Column('training_load', sa.Float(), nullable=False),
    sa.Column('ctl', sa.Float(), nullable=False),
    sa.Column('atl', sa.Float(), nullable=False),
    sa.Column('tsb', sa.Float(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'local_date', name='uq_fitness_daily_rollup_identity')
    )
    op.create_table('health_metric_period_rollup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.String(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('value_sum', sa.Float(), nullable=True),
    sa.Column('value_avg', sa.Float(), nullable=True),
    sa.Column('value_min', sa.Float(), nullable=True),
    sa.Column('value_max', sa.Float(), nullable=True),
    sa.Column('value_last', sa.Float(), nullable=True),
    sa.Column('n_observations', sa.Integer(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['metric_key'], ['metric_definition.metric_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'period_type', 'period_start', 'metric_key', name='uq_health_period_rollup_identity')
    )
    with op.batch_alter_table('health_metric_period_rollup', schema=None) as batch_op:
        batch_op.create_index('ix_health_period_rollup_athlete_period', ['athlete_id', 'period_type', 'period_start'], unique=False)

    op.create_table('period_rollup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.String(), nullable=False),
    sa.Column('period_end', sa.String(), nullable=False),
    sa.Column('activity_count', sa.Integer(), nullable=False),
    sa.Column('activity_duration_s', sa.Float(), nullable=True),
    sa.Column('activity_moving_duration_s', sa.Float(), nullable=True),
    sa.Column('activity_distance_m', sa.Float(), nullable=True),
    sa.Column('activity_elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('activity_calories', sa.Float(), nullable=True),
    sa.Column('activity_days_count', sa.Integer(), nullable=False),
    sa.Column('sleep_total_s', sa.Float(), nullable=True),
    sa.Column('sleep_score', sa.Float(), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'period_type', 'period_start', name='uq_period_rollup_identity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('period_rollup')
    with op.batch_alter_table('health_metric_period_rollup', schema=None) as batch_op:
        batch_op.drop_index('ix_health_period_rollup_athlete_period')

    op.drop_table('health_metric_period_rollup')
    op.drop_table('fitness_daily_rollup')
    # ### end Alembic commands ###
