"""Add activity.max_altitude_m

Revision ID: bc2cb42cdd7e
Revises: cf9ec1060c83
Create Date: 2026-08-23 23:08:19.430246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2cb42cdd7e'
down_revision: Union[str, Sequence[str], None] = 'cf9ec1060c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_altitude_m', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('max_altitude_m')

    # ### end Alembic commands ###
