"""add insight table

Revision ID: c9dafedd2059
Revises: a6c58d78f6fc
Create Date: 2026-08-14 23:18:58.453557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9dafedd2059'
down_revision: Union[str, Sequence[str], None] = 'a6c58d78f6fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('window', sa.String(), nullable=False),
    sa.Column('subject_key', sa.String(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=True),
    sa.Column('sport_family', sa.String(), nullable=True),
    sa.Column('activity_id', sa.String(length=26), nullable=True),
    sa.Column('local_date', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'kind', 'window', 'subject_key', name='uq_insight_identity')
    )
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.create_index('ix_insight_athlete_kind_window', ['athlete_id', 'kind', 'window'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.drop_index('ix_insight_athlete_kind_window')

    op.drop_table('insight')
    # ### end Alembic commands ###
