"""add athlete last_full_export_at

Revision ID: c9ebfc30ba99
Revises: 35c217c541f2
Create Date: 2026-08-02 21:22:20.046973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ebfc30ba99'
down_revision: Union[str, Sequence[str], None] = '35c217c541f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_full_export_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.drop_column('last_full_export_at')

    # ### end Alembic commands ###
