"""Add activity_merge_override

Revision ID: cf9ec1060c83
Revises: 4a71a0e55c10
Create Date: 2026-08-23 21:31:36.452717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9ec1060c83'
down_revision: Union[str, Sequence[str], None] = '4a71a0e55c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_merge_override',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('keep_source', sa.String(), nullable=False),
    sa.Column('keep_external_id', sa.String(), nullable=False),
    sa.Column('absorbed_source', sa.String(), nullable=False),
    sa.Column('absorbed_external_id', sa.String(), nullable=False),
    sa.Column('field_choices', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'absorbed_source', 'absorbed_external_id', name='uq_activity_merge_override_absorbed_identity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_merge_override')
    # ### end Alembic commands ###
