"""widen activity_sport_override with nullable sport and is_race

Revision ID: d553c2e39bc5
Revises: 3a24511b2278
Create Date: 2026-08-15 13:46:41.989372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd553c2e39bc5'
down_revision: Union[str, Sequence[str], None] = '3a24511b2278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_sport_override', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_race', sa.Boolean(), nullable=True))
        batch_op.alter_column('sport',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_sport_override', schema=None) as batch_op:
        batch_op.alter_column('sport',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('is_race')

    # ### end Alembic commands ###
