"""add comment to planned_workout_step

Revision ID: d684d049035b
Revises: 2e16e2853432
Create Date: 2026-09-06 19:14:59.339380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd684d049035b'
down_revision: Union[str, Sequence[str], None] = '2e16e2853432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planned_workout_step', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planned_workout_step', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
