"""add activity_metric athlete/metric_key index

The existing uniqueness index on activity_metric leads with (athlete_id, activity_id,
metric_key, source), so it can't serve "every row for this athlete carrying one specific
metric_key, across every activity" -- exactly what vo2max_analysis.py's own request-time factor-
analysis query needs, and what performance_rollup.py's own full-history VDOT read has always
needed too, just never at request time before. Confirmed live via EXPLAIN QUERY PLAN and direct
timing against the real ~1,400-day database: 33s cold (a full per-athlete scan across every
metric ever recorded) down to 0.002s with this index. Additive, no backfill (an index needs no
data migration, just building).

Revision ID: d906425621ea
Revises: aad9cbbed3d3
Create Date: 2026-09-12 20:17:13.185799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd906425621ea'
down_revision: Union[str, Sequence[str], None] = 'aad9cbbed3d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_metric', schema=None) as batch_op:
        batch_op.create_index('ix_activity_metric_athlete_key', ['athlete_id', 'metric_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_metric', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_metric_athlete_key')

    # ### end Alembic commands ###
