"""add athlete_email_report_config

Revision ID: d9f41d56aea6
Revises: 17c9c6538b90
Create Date: 2026-09-09 22:13:26.872224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f41d56aea6'
down_revision: Union[str, Sequence[str], None] = '17c9c6538b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Per-athlete opt-in for the weekly/monthly training-report emails (email_reports.py) --
    one row per athlete, both flags default False (no row == no emails). The SMTP relay is
    deployment-global (PERSEVERER_SMTP_*) and the recipient is athlete.email; this table is only
    the two switches. Additive, no backfill."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_email_report_config',
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('weekly_enabled', sa.Boolean(), nullable=False),
    sa.Column('monthly_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('athlete_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('athlete_email_report_config')
    # ### end Alembic commands ###
