"""add activity_sport_override table

Revision ID: e2a52f71176e
Revises: c9dafedd2059
Create Date: 2026-08-15 12:46:15.757057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a52f71176e'
down_revision: Union[str, Sequence[str], None] = 'c9dafedd2059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_sport_override',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('start_time_utc', sa.DateTime(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('sub_sport', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'start_time_utc', name='uq_activity_sport_override_identity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_sport_override')
    # ### end Alembic commands ###
