// Data access for the /exercises page (ExerciseLibraryPage.tsx) -- the browsable reference for
// every exercise the hiit/strength_training picker supports, generated by
// scripts/generate_exercise_library.py into data/exerciseLibrary.json. Kept as a dynamic
// import, like ExerciseStepEditor.tsx's own exercise catalog, so this ~1MB reference data
// (photos hotlinked, not embedded, but descriptions/muscle data for all 1,527 entries add up)
// never lands in the main app-shell bundle -- only fetched when this page is actually opened.
export interface ExerciseLibraryEntry {
  name: string;
  category: string;
  categoryLabel: string;
  exercise: string;
  // Only set for tier 1 -- Garmin's own exercise pages sit entirely behind a sign-in wall, and
  // confirmed live (2026-09) that a non-detailed exercise's page hangs on an infinite loading
  // spinner even once signed in, while a detailed one loads its real video/steps/tips
  // correctly. Rather than link to a page that plausibly never loads, only the exercises this
  // app knows for certain have real Garmin content get a link at all.
  garmin_url: string | null;
  primary_muscles: string[];
  secondary_muscles: string[];
  // 1: Garmin's own photo + description (a real "detailed" exercise on Garmin's own site).
  // 2: a free-exercise-db photo + instructions, matched by name -- see matched_exercise_name.
  // 3: no photo exists for this exercise specifically; description is muscle groups only.
  tier: 1 | 2 | 3;
  image_url: string | null;
  image_source: "garmin" | "free-exercise-db" | null;
  description: string | null;
  difficulty: string | null;
  // tier 2 only, and only worth showing when it differs from `name` -- the photo/instructions
  // belong to this closely-related exercise, not necessarily the exact named variant.
  matched_exercise_name?: string;
  // Step-by-step instructions, when they exist as discrete steps rather than one description
  // paragraph: tier 2's free-exercise-db match already carries its instructions as a real list
  // (previously flattened into `description`, now kept structured), and a small hand-curated
  // set of tier 3's own generic "family" exercises (ones whose name IS the category -- "Row",
  // "Lateral Raise", "Battle Rope", etc. -- a real single technique, not one of many differently-
  // named variants Garmin never photographed) get originally-written steps here too. Never
  // present for tier 1 -- Garmin's own description is already prose, not a step list.
  steps?: string[] | null;
  // Only set alongside a hand-curated `steps` entry above -- a single external page/video for
  // further reading, deliberately never a copied description or image (exrx.net/darebee.com's
  // own terms don't permit reproducing their content at this catalog's scale; a plain hyperlink
  // is a different, uncontroversial thing).
  reference_url?: string | null;
  reference_label?: string | null;
}

let libraryPromise: Promise<ExerciseLibraryEntry[]> | null = null;

export function loadExerciseLibrary(): Promise<ExerciseLibraryEntry[]> {
  libraryPromise ??= import("./data/exerciseLibrary.json").then(
    (mod) => mod.default as ExerciseLibraryEntry[],
  );
  return libraryPromise;
}
