"""An athlete's own manual corrections: sport, race status, the activity's own name, and/or its
fueling intake.

**Sport correction** -- real, confirmed need: several activities in this athlete's archive are
FIT files generated by a third-party tool ("Sauce for Strava", confirmed via
`fit.file_id.product_name`) that reconstructs FIT bytes from Strava's own activity data -- and
writes `sport=running` into every one of them regardless of what the activity actually was (a
23.7 min/km "run" is really a hike; several 12-18 min/km "runs" are really walks). Unlike
`garmin_activity_summary.py`'s correction, there's no second raw source in this athlete's
archive to cross-check against for these -- the athlete is the only one who actually knows what
the activity was, so this is a genuinely manual, out-of-band correction.

**Race correction** -- same shape of problem, different field: `garmin_activity_summary.py`'s
`is_race` heuristic is only as good as Garmin Connect's own `eventTypeId`, which reflects
whether the athlete flagged the activity as a race *inside the Garmin Connect app* -- a real
race the athlete never flagged there (confirmed against this athlete's own archive: a "San
Francisco - Marathon" activity with `eventTypeId=9`, the generic default, not `1`) has no other
signal in the raw data to derive it from. Same fix, same mechanism.

**Name correction** -- same shape again, but with no automatic fix at all: an earlier attempt
at `garmin_activity_summary.py` broadened its `name` correction to always trust Garmin
Connect's own name over the FIT-derived on-device default, on the (wrong) assumption that
Garmin's own name is always a real athlete-given title. Run for real, it mass-overwrote 396
activities' names with a single generic Garmin auto-title ("Santa Clara Other" -- a
location+activity-type template, not anything the athlete typed) that was no more informative
than the FIT default it replaced, sometimes less. That change was reverted; there is no reliable
automatic signal in this athlete's data for "Garmin's name here is a real title, not a
template," so fixing a boring name (e.g. "Run") is a manual, per-activity call only the athlete
can make -- same as the sport and race corrections above.

**Fueling** -- a different shape of problem: not a correction of a wrong or missing derived
value, but data with no vendor source at all. Neither the FIT profile (introspected directly,
per this project's own "verify against the installed package" discipline) nor the Garmin Connect
API (`get_activity`/`get_activity_details`, both checked against real activities live) carry
carbohydrate or sodium fields -- there's nothing to correct, so this is the athlete's own input
from the start, recorded the same durable way as the other three.

None of these corrections can be a direct `UPDATE activity SET ... = ...` the way
`garmin_activity_summary.py`'s correction is: `sync rebuild` deletes and re-inserts every
`activity` row from the raw archive, so a bare mutation would silently vanish on the next
rebuild -- a real "raw first" violation for data that isn't derivable from raw bytes at all.
`activity_sport_override` is the durable record instead (never wiped by rebuild -- see
rebuild.py's `_REBUILDABLE_TABLES`), and `apply_sport_overrides` re-applies it as a correction
pass, exactly mirroring how `correct_activities_from_summary` re-applies Garmin's own corrections
-- just sourced from the athlete's own input instead of a second vendor file. `sport`, `is_race`,
`name`, and `carbohydrates_g`/`sodium_mg` are set independently: setting one never touches the
others, whether that's a fresh row or updating an existing correction.

Keyed by `start_time_utc`, not `activity.id`: the id is a fresh ULID minted on every rebuild
(the row is deleted and re-created), so it isn't stable across rebuilds. `start_time_utc` is --
it's parsed straight out of the same archived bytes every time, so it reliably identifies "the
same physical activity" run after run.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import cast

from sqlalchemy import Connection, select
from sqlalchemy.dialects.sqlite import insert as sqlite_insert

from perseverer.db.schema import activity, activity_sport_override


def _start_time_for(conn: Connection, *, athlete_id: str, activity_id: str) -> datetime:
    row = conn.execute(
        select(activity.c.start_time_utc).where(
            activity.c.id == activity_id, activity.c.athlete_id == athlete_id
        )
    ).fetchone()
    if row is None:
        raise ValueError(f"no activity {activity_id!r} for athlete {athlete_id!r}")
    return cast(datetime, row.start_time_utc)


def set_sport_override(
    conn: Connection, *, athlete_id: str, activity_id: str, sport: str, sub_sport: str | None
) -> None:
    """Records the correction (upserting on the athlete/start_time_utc identity, so re-fixing an
    already-corrected activity just replaces the previous sport correction, leaving any separate
    `is_race` correction on the same row untouched) and applies it to this one activity
    immediately, rather than waiting for the next `sync rebuild`."""
    start_time_utc = _start_time_for(conn, athlete_id=athlete_id, activity_id=activity_id)

    now = datetime.now(UTC).replace(tzinfo=None)
    stmt = sqlite_insert(activity_sport_override).values(
        athlete_id=athlete_id,
        start_time_utc=start_time_utc,
        sport=sport,
        sub_sport=sub_sport,
        created_at=now,
    )
    conn.execute(
        stmt.on_conflict_do_update(
            index_elements=["athlete_id", "start_time_utc"],
            set_={"sport": sport, "sub_sport": sub_sport, "created_at": now},
        )
    )
    conn.execute(
        activity.update()
        .where(activity.c.id == activity_id)
        .values(sport=sport, sub_sport=sub_sport, updated_at=now)
    )


def set_race_override(
    conn: Connection, *, athlete_id: str, activity_id: str, is_race: bool
) -> None:
    """Same shape as `set_sport_override`, for the athlete's own "this is/isn't a race"
    correction -- upserts on the athlete/start_time_utc identity without touching any separate
    sport correction already recorded on that same row, and applies immediately."""
    start_time_utc = _start_time_for(conn, athlete_id=athlete_id, activity_id=activity_id)

    now = datetime.now(UTC).replace(tzinfo=None)
    stmt = sqlite_insert(activity_sport_override).values(
        athlete_id=athlete_id,
        start_time_utc=start_time_utc,
        is_race=is_race,
        created_at=now,
    )
    conn.execute(
        stmt.on_conflict_do_update(
            index_elements=["athlete_id", "start_time_utc"],
            set_={"is_race": is_race, "created_at": now},
        )
    )
    conn.execute(
        activity.update()
        .where(activity.c.id == activity_id)
        .values(is_race=is_race, updated_at=now)
    )


def set_name_override(conn: Connection, *, athlete_id: str, activity_id: str, name: str) -> None:
    """Same shape as `set_sport_override`/`set_race_override`, for the athlete's own "this
    title is wrong" correction -- upserts on the athlete/start_time_utc identity without
    touching any separate sport/race correction already recorded on that same row, and applies
    immediately."""
    start_time_utc = _start_time_for(conn, athlete_id=athlete_id, activity_id=activity_id)

    now = datetime.now(UTC).replace(tzinfo=None)
    stmt = sqlite_insert(activity_sport_override).values(
        athlete_id=athlete_id,
        start_time_utc=start_time_utc,
        name=name,
        created_at=now,
    )
    conn.execute(
        stmt.on_conflict_do_update(
            index_elements=["athlete_id", "start_time_utc"],
            set_={"name": name, "created_at": now},
        )
    )
    conn.execute(
        activity.update().where(activity.c.id == activity_id).values(name=name, updated_at=now)
    )


def set_fueling_override(
    conn: Connection,
    *,
    athlete_id: str,
    activity_id: str,
    carbohydrates_g: float | None,
    sodium_mg: float | None,
) -> None:
    """Records the athlete's own carbohydrate/sodium intake for this activity -- same shape as
    `set_sport_override`/`set_race_override`/`set_name_override`, upserting on the
    athlete/start_time_utc identity without touching any separate correction already recorded on
    that same row, and applying immediately. Unlike the other three, there's nothing to
    "correct" here (see module docstring) -- this is the athlete's only source for this data."""
    start_time_utc = _start_time_for(conn, athlete_id=athlete_id, activity_id=activity_id)

    now = datetime.now(UTC).replace(tzinfo=None)
    stmt = sqlite_insert(activity_sport_override).values(
        athlete_id=athlete_id,
        start_time_utc=start_time_utc,
        carbohydrates_g=carbohydrates_g,
        sodium_mg=sodium_mg,
        created_at=now,
    )
    conn.execute(
        stmt.on_conflict_do_update(
            index_elements=["athlete_id", "start_time_utc"],
            set_={
                "carbohydrates_g": carbohydrates_g,
                "sodium_mg": sodium_mg,
                "created_at": now,
            },
        )
    )
    conn.execute(
        activity.update()
        .where(activity.c.id == activity_id)
        .values(carbohydrates_g=carbohydrates_g, sodium_mg=sodium_mg, updated_at=now)
    )


def apply_sport_overrides(conn: Connection, *, athlete_id: str) -> int:
    """Re-applies every recorded correction (sport, race, name, and/or fueling) -- called at the
    end of `sync rebuild` so a manual correction survives a full wipe-and-replay. Matches by exact
    `start_time_utc` equality (not a tolerance window like the Garmin-summary correction's
    cross-source timestamp matching): both sides come from the same archived bytes, so they're
    identical down to the second, not just close. Only the columns actually recorded on a given
    override row are written -- a race-only correction never overwrites `sport`/`sub_sport` back
    to null, and vice versa. Returns the number of activities corrected."""
    overrides = conn.execute(
        select(
            activity_sport_override.c.start_time_utc,
            activity_sport_override.c.sport,
            activity_sport_override.c.sub_sport,
            activity_sport_override.c.is_race,
            activity_sport_override.c.name,
            activity_sport_override.c.carbohydrates_g,
            activity_sport_override.c.sodium_mg,
        ).where(activity_sport_override.c.athlete_id == athlete_id)
    ).fetchall()
    if not overrides:
        return 0

    now = datetime.now(UTC).replace(tzinfo=None)
    corrected = 0
    for o in overrides:
        values: dict[str, object] = {"updated_at": now}
        if o.sport is not None:
            values["sport"] = o.sport
            values["sub_sport"] = o.sub_sport
        if o.is_race is not None:
            values["is_race"] = o.is_race
        if o.name is not None:
            values["name"] = o.name
        if o.carbohydrates_g is not None:
            values["carbohydrates_g"] = o.carbohydrates_g
        if o.sodium_mg is not None:
            values["sodium_mg"] = o.sodium_mg
        result = conn.execute(
            activity.update()
            .where(
                activity.c.athlete_id == athlete_id,
                activity.c.start_time_utc == o.start_time_utc,
                activity.c.deleted_at.is_(None),
            )
            .values(**values)
        )
        corrected += result.rowcount
    return corrected
